import React, { useState, useMemo, useEffect } from "react";
import { AllContactsTab } from './AllContactsTab';
import { StaffTab } from './StaffTab';

import { ContactFormModal } from './ContactFormModal';

import { createPortal } from "react-dom";
import { ImportExportButtons } from "../../../shared/ImportExportButtons";
import { useFormSettings } from "../../../../useFormSettings";
import {
  AddIcon,
  EditIcon,
  DeleteIcon,
  SearchIcon,
  CancelIcon,
} from "../../../icons/IconComponents";
import { CustomersTab } from "./CustomersTab";
import { VendorsTab } from "./VendorsTab";
import { PartnersTab } from "./PartnersTab";
import { ChevronDown, ChevronUp, Fingerprint , Edit2, Trash2} from 'lucide-react';
import { motion, AnimatePresence } from "motion/react";

const DEPARTMENT_DESIGNATION_MAP: Record<string, string[]> = {
  Management: [
    "General Manager & Operations Director",
    "Chief Executive Officer (CEO)",
    "Chief Operating Officer (COO)",
    "Operations Director",
    "Administrative Head",
  ],
  "Marketing & Ad": [
    "Lead Digital Advertiser & Brand Strategist",
    "PPC & AdWords Marketing Consultant",
    "Digital Marketing Executive",
    "Social Media Campaign Manager",
    "Ad Copywriter & Content Marketer",
  ],
  Finance: [
    "Finance & Taxation Manager",
    "Senior Accountant & Bookkeeper",
    "Accounts Assistant",
    "Auditor & Tax Consultant",
    "Billing & Invoice Specialist",
  ],
  Publishing: [
    "Publisher Relations Specialist",
    "Acquisitions & Contracting Manager",
    "Rights & Licensing Director",
    "Publishing Operations Supervisor",
  ],
  "Logistics & Supply": [
    "Warehouse & Inventory Supervisor",
    "Logistics & Distribution Coordinator",
    "Storekeeper",
    "Inventory Auditor & Quality Analyst",
  ],
  "Customer Success": [
    "Senior Customer Relations Manager",
    "Customer Success Executive",
    "Technical Support Specialist",
    "Customer Helpdesk Coordinator",
  ],
  "Human Resources": [
    "Human Resources & Payroll Lead",
    "HR Operations Manager",
    "Talent Acquisition & Onboarding executive",
    "Recruitment & Training Coordinator",
  ],
  "Sales & Distribution": [
    "Sales & Retail Channel Manager",
    "Channel Distribution Specialist",
    "Institutional Sales Consultant",
    "Retail Relations Executive",
  ],
  "Editorial & Content": [
    "Senior Editorial & Content Acquisition Head",
    "Acquisition Editor",
    "Senior Proofreader & Fact-checker",
    "Royalty Specialist",
  ],
  "Information Technology": [
    "Principal System & DevOps Engineer",
    "Systems & Network Administrator",
    "IT Support Team Lead",
    "Database Administrator",
    "OCR Integration Developer",
  ],
};

const DEPARTMENT_OPTIONS = Object.keys(DEPARTMENT_DESIGNATION_MAP);

const getAutoGeneratedCode = (
  type: "Staff" | "Customer" | "Vendor" | "Partner",
  data: any[],
  partyMasters: any[],
) => {
  if (type === "Staff") {
    const currentStaff = (data || []).filter(
      (m) =>
        m.contactType === "Internal" ||
        m.contactType === "Contract" ||
        m.contactType === "External" ||
        !m.contactType,
    );
    const count = currentStaff.length + 1;
    return `STF-${String(count).padStart(3, "0")}`;
  } else if (type === "Customer") {
    const currentCust = (partyMasters || []).filter(
      (m) => m.type === "Customer" || !m.type,
    );
    const count = currentCust.length + 1;
    return `CUST-${String(count).padStart(3, "0")}`;
  } else if (type === "Vendor") {
    const currentVend = (partyMasters || []).filter((m) => m.type === "Vendor");
    const count = currentVend.length + 1;
    return `VND-${String(count).padStart(3, "0")}`;
  } else if (type === "Partner") {
    const currentParts = (partyMasters || []).filter((m) => m.type === "Both");
    const count = currentParts.length + 1;
    return `PRT-${String(count).padStart(3, "0")}`;
  }
  return `CON-${Date.now()}`;
};

const getDeptAbbreviation = (dept: string): string => {
  switch (dept) {
    case "Management":
      return "MAN";
    case "Marketing & Ad":
      return "ADV";
    case "Finance":
      return "FIN";
    case "Publishing":
      return "PUB";
    case "Logistics & Supply":
      return "OPS";
    case "Customer Success":
      return "CS";
    case "Human Resources":
      return "HR";
    case "Sales & Distribution":
      return "SAL";
    case "Editorial & Content":
      return "EDT";
    case "Information Technology":
      return "SYS";
    case "Audit & Law":
      return "AUD";
    default:
      return dept ? dept.substring(0, 3).toUpperCase() : "";
  }
};

const generateStaffCode = (dept: string, allContacts: any[]) => {
  const abbrev = getDeptAbbreviation(dept);
  if (!abbrev) return "";

  const prefix = `STF-${abbrev}-`;
  let maxSeq = 0;
  (allContacts || []).forEach((c) => {
    if (c.code && c.code.startsWith(prefix)) {
      const suffix = c.code.replace(prefix, "");
      const num = parseInt(suffix, 10);
      if (!isNaN(num) && num > maxSeq) {
        maxSeq = num;
      }
    }
  });
  const nextSeq = maxSeq + 1;
  return `${prefix}${String(nextSeq).padStart(2, "0")}`;
};

interface ContactsTabProps {
  data: any[]; // contactMasters
  onSave: (items: any[]) => void; // setContactMasters
  partyMasters?: any[];
  setPartyMasters?: (items: any[]) => void;
}

export const ContactsTab: React.FC<ContactsTabProps> = ({
  data,
  onSave,
  partyMasters = [],
  setPartyMasters,
}) => {
  const [searchTerm, setSearchTerm] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState<any>({});
  const [deleteConfirmation, setDeleteConfirmation] = useState<{
    isOpen: boolean;
    id: string;
    name: string;
    type: string;
  } | null>(null);
  const [subTab, setSubTab] = useState<
    "all" | "staff" | "customers" | "vendors" | "partners"
  >("all");
  const formSettings = useFormSettings();

  // Accordion state - only one section can be open at a time, collapsed by default
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>, fieldName: string) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData((prev: any) => ({ ...prev, [fieldName]: reader.result }));
      };
      reader.readAsDataURL(file);
    }
  };

  // Reset accordion to collapsed when modal is opened or closed
  React.useEffect(() => {
    setExpandedSection(null);
  }, [isModalOpen]);

  // Sync React effect to automatically generate the code when details are modified
  React.useEffect(() => {
    // Only run when creating a new contact (not editing)
    if (isModalOpen && !editingId) {
      if (formData.unifiedType === "Staff" || !formData.unifiedType) {
        if (
          formData.department &&
          formData.department !== "Custom Department"
        ) {
          const generated = generateStaffCode(formData.department, data);
          if (generated && formData.code !== generated) {
            setFormData((prev: any) => ({ ...prev, code: generated }));
          }
        } else if (!formData.department) {
          if (formData.code !== "") {
            setFormData((prev: any) => ({ ...prev, code: "" }));
          }
        }
      } else {
        // For Customer, Vendor, Partner, generate based on their classifications if empty
        const generated = getAutoGeneratedCode(
          formData.unifiedType,
          data,
          partyMasters,
        );
        if (generated && formData.code !== generated && !formData.code) {
          setFormData((prev: any) => ({ ...prev, code: generated }));
        }
      }
    }
  }, [
    formData.department,
    formData.unifiedType,
    isModalOpen,
    editingId,
    data,
    partyMasters,
  ]);

  // Deduce lists for Customers, Vendors, and Partners from partyMasters
  const customers = useMemo(
    () => (partyMasters || []).filter((m) => m.type === "Customer" || !m.type),
    [partyMasters],
  );
  const vendors = useMemo(
    () => (partyMasters || []).filter((m) => m.type === "Vendor"),
    [partyMasters],
  );
  const partners = useMemo(
    () => (partyMasters || []).filter((m) => m.type === "Both"),
    [partyMasters],
  );

  // Save callbacks that propagate changes back to partyMasters
  const saveCustomers = (newC: any[]) => {
    if (setPartyMasters) {
      setPartyMasters([...newC, ...vendors, ...partners]);
    }
  };

  const saveVendors = (newV: any[]) => {
    if (setPartyMasters) {
      setPartyMasters([...newV, ...customers, ...partners]);
    }
  };

  const savePartners = (newP: any[]) => {
    if (setPartyMasters) {
      setPartyMasters([...newP, ...customers, ...vendors]);
    }
  };

  // Filter staff / internal contacts
  const filteredStaffData = useMemo(() => {
    const staffList = (data || []).filter(
      (m: any) =>
        m.contactType === "Internal" ||
        m.contactType === "Contract" ||
        m.contactType === "External" ||
        !m.contactType,
    );
    return staffList.filter((m: any) => {
      const search = searchTerm.toLowerCase();
      return (
        String(m.name || "")
          .toLowerCase()
          .includes(search) ||
        String(m.code || "")
          .toLowerCase()
          .includes(search) ||
        String(m.designation || "")
          .toLowerCase()
          .includes(search) ||
        String(m.department || "")
          .toLowerCase()
          .includes(search) ||
        String(m.description || "")
          .toLowerCase()
          .includes(search) ||
        String(m.email || "")
          .toLowerCase()
          .includes(search) ||
        String(m.phone || "")
          .toLowerCase()
          .includes(search)
      );
    });
  }, [data, searchTerm]);

  // Gather all contacts at once (Staff + Customers + Vendors + Partners)
  const allContactsCombined = useMemo(() => {
    const staffList = (data || []).map((m: any) => ({
      ...m,
      unifiedType: "Staff",
      classification:
        m.contactType === "Contract" ? "Contract Staff" : "Internal Staff",
    }));

    const customerList = customers.map((m: any) => ({
      ...m,
      unifiedType: "Customer",
      classification: "Customer",
    }));

    const vendorList = vendors.map((m: any) => ({
      ...m,
      unifiedType: "Vendor",
      classification: "Vendor",
    }));

    const partnerList = partners.map((m: any) => ({
      ...m,
      unifiedType: "Partner",
      classification: "Partner",
    }));

    return [...staffList, ...customerList, ...vendorList, ...partnerList];
  }, [data, customers, vendors, partners]);

  // Filter unified list
  const filteredAllContacts = useMemo(() => {
    return allContactsCombined.filter((m: any) => {
      const search = searchTerm.toLowerCase();
      return (
        String(m.name || "")
          .toLowerCase()
          .includes(search) ||
        String(m.code || "")
          .toLowerCase()
          .includes(search) ||
        String(m.classification || "")
          .toLowerCase()
          .includes(search) ||
        String(m.phone || "")
          .toLowerCase()
          .includes(search) ||
        String(m.email || "")
          .toLowerCase()
          .includes(search) ||
        String(m.designation || "")
          .toLowerCase()
          .includes(search) ||
        String(m.department || "")
          .toLowerCase()
          .includes(search)
      );
    });
  }, [allContactsCombined, searchTerm]);

  const handleSaveUnified = () => {
    if (!formData.name?.trim() && !formData.code?.trim()) return;

    const uType = formData.unifiedType || "Staff";

    if (uType === "Staff") {
      const contactTypeVal = formData.contactType || "Internal";
      const addressParts = [
        formData.streetAddress,
        formData.district,
        formData.city,
        formData.state,
        formData.country,
        formData.zipCode,
      ]
        .map((s) => s?.trim())
        .filter(Boolean);
      const constructedAddress = addressParts.join(", ");

      const contactToSave = {
        ...formData,
        id: editingId || `item-${Date.now()}`,
        contactType: contactTypeVal,
        address: constructedAddress || formData.address || "",
        resignationDate:
          formData.status === "Inactive" || formData.status === "Resigned"
            ? formData.resignationDate || ""
            : "",
        resignationReason:
          formData.status === "Inactive" || formData.status === "Resigned"
            ? formData.resignationReason || ""
            : "",
        resignationDescription:
          formData.status === "Inactive" || formData.status === "Resigned"
            ? formData.resignationDescription || ""
            : "",
      };
      const newList = editingId
        ? data.map((m: any) => (m.id === editingId ? contactToSave : m))
        : [...data, contactToSave];
      onSave(newList);
    } else {
      // Party Master (Customer / Vendor / Partner)
      const partyTypeVal = uType === "Partner" ? "Both" : uType;
      const partyToSave = {
        id: editingId || `item-${Date.now()}`,
        code: formData.code,
        name: formData.name,
        type: partyTypeVal,
        description: formData.description || formData.notes || "",
        gstin: formData.gstin || "",
        panNo: formData.panNo || "",
        contactPerson: formData.contactPerson || "",
        phone: formData.phone || "",
        email: formData.email || "",
        address: formData.address || "",
        city: formData.city || "",
        state: formData.state || "",
        pincode: formData.pincode || "",
        creditDays: formData.creditDays || 0,
        openingBalance: formData.openingBalance || 0,
        balanceType: formData.balanceType || "Debit",
        bankName: formData.bankName || "",
        bankAccountNo: formData.bankAccountNo || "",
        ifscCode: formData.ifscCode || "",
      };

      if (setPartyMasters) {
        const newList = editingId
          ? partyMasters.map((m: any) => (m.id === editingId ? partyToSave : m))
          : [...partyMasters, partyToSave];
        setPartyMasters(newList);
      }
    }

    setIsModalOpen(false);
    setEditingId(null);
    setFormData({});
  };

  const confirmDeleteUnified = () => {
    if (!deleteConfirmation) return;
    const { id, type } = deleteConfirmation;

    if (type === "Staff") {
      onSave(data.filter((m: any) => m.id !== id));
    } else {
      if (setPartyMasters) {
        setPartyMasters(partyMasters.filter((m: any) => m.id !== id));
      }
    }
    setDeleteConfirmation(null);
  };

  const renderClassificationBadge = (item: any) => {
    if (item.unifiedType === "Staff") {
      const isContract = item.contactType === "Contract";
      return (
        <span
          className={`px-2.5 py-1 text-[10px] font-bold rounded-lg border ${
            isContract
              ? "bg-amber-50 text-amber-700 border-amber-100 dark:bg-amber-900/20 dark:text-amber-400 dark:border-amber-800"
              : "bg-teal-50 text-teal-700 border-teal-100 dark:bg-teal-900/20 dark:text-teal-400 dark:border-teal-800"
          }`}
        >
          {isContract ? "Contract Staff" : "Internal Staff"}
        </span>
      );
    }
    if (item.classification === "Customer") {
      return (
        <span className="px-2.5 py-1 text-[10px] font-bold rounded-lg bg-emerald-50 text-emerald-700 border border-emerald-100 dark:bg-emerald-900/20 dark:text-emerald-400 dark:border-emerald-800">
          Customer
        </span>
      );
    }
    if (item.classification === "Vendor") {
      return (
        <span className="px-2.5 py-1 text-[10px] font-bold rounded-lg bg-rose-50 text-rose-700 border border-rose-100 dark:bg-rose-900/20 dark:text-rose-400 dark:border-rose-800">
          Vendor
        </span>
      );
    }
    if (item.classification === "Partner") {
      return (
        <span className="px-2.5 py-1 text-[10px] font-bold rounded-lg bg-indigo-50 text-indigo-700 border border-indigo-100 dark:bg-indigo-900/20 dark:text-indigo-400 dark:border-indigo-800">
          Partner
        </span>
      );
    }
    return null;
  };

  const renderDetailsCell = (item: any) => {
    if (item.unifiedType === "Staff") {
      const isResigned =
        item.status === "Inactive" || item.status === "Resigned";
      return (
        <div className="text-sm">
          {item.designation && (
            <div className="font-semibold text-blue-700 dark:text-blue-400 text-xs uppercase tracking-wide flex items-center gap-1.5 flex-wrap">
              <span>{item.designation}</span>
              <span className="text-gray-400 font-normal">
                ({item.department || "No Dept"})
              </span>
              {item.gender && (
                <span
                  className={`px-1 py-0.5 border rounded text-[9px] font-bold flex items-center gap-0.5 ${
                    item.gender === "Female"
                      ? "bg-pink-50 text-pink-700 border-pink-100 dark:bg-pink-950/20 dark:text-pink-400 dark:border-pink-900/50"
                      : "bg-indigo-50 text-indigo-700 border-indigo-150 dark:bg-indigo-950/20 dark:text-indigo-400 dark:border-indigo-950/30"
                  }`}
                >
                  👤 {item.gender}
                </span>
              )}
              {item.bloodGroup && (
                <span className="px-1 py-0.5 bg-red-50 text-rose-700 border border-red-100 rounded text-[9px] font-bold flex items-center gap-1 dark:bg-red-950/20 dark:text-red-400 dark:border-red-900/50">
                  🩸 {item.bloodGroup}
                </span>
              )}
            </div>
          )}
          <div className="flex flex-wrap gap-x-2 gap-y-0.5 text-[11px] text-gray-400 font-mono mt-0.5">
            {item.phone && <span>{item.phone}</span>}
            {item.email && <span>• {item.email}</span>}
            {item.alternatePhone && (
              <span className="text-gray-500 dark:text-gray-400">
                • Alt: {item.alternatePhone}
                {item.alternateRelation ? ` (${item.alternateRelation})` : ""}
              </span>
            )}
          </div>
          {(item.aadhaarCard || item.panCard || item.voterIdCard || item.drivingLicense) && (
            <div className="flex flex-wrap gap-1 mt-1 pt-1 border-t border-gray-100 dark:border-gray-800">
              {item.aadhaarCard && (
                <span
                  className="inline-flex items-center gap-0.5 px-1 py-0.5 bg-slate-50 text-slate-700 border border-slate-200 rounded text-[9px] font-mono dark:bg-slate-900 dark:text-slate-300 dark:border-slate-800"
                  title="Aadhaar Card"
                >
                  🆔 {item.aadhaarCard}
                </span>
              )}
              {item.panCard && (
                <span
                  className="inline-flex items-center gap-0.5 px-1 py-0.5 bg-indigo-50 text-indigo-700 border border-indigo-200 rounded text-[9px] font-mono dark:bg-indigo-900 dark:text-indigo-300 dark:border-indigo-800"
                  title="PAN Card"
                >
                  💳 {item.panCard}
                </span>
              )}
              {item.voterIdCard && (
                <span
                  className="inline-flex items-center gap-0.5 px-1 py-0.5 bg-sky-50 text-sky-700 border border-sky-200 rounded text-[9px] font-mono dark:bg-sky-950/40 dark:text-sky-300 dark:border-sky-800"
                  title="Voter ID Card"
                >
                  🗳️ {item.voterIdCard}
                </span>
              )}
              {item.drivingLicense && (
                <span
                  className="inline-flex items-center gap-0.5 px-1 py-0.5 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded text-[9px] font-mono dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800"
                  title="Driving License"
                >
                  🚗 {item.drivingLicense}
                </span>
              )}
            </div>
          )}
          {isResigned && (
            <div className="text-[10px] text-rose-600 dark:text-rose-400 font-semibold font-mono mt-1">
              Resigned / Left on: {item.resignationDate || "N/A"}
            </div>
          )}
        </div>
      );
    }
    return (
      <div className="text-sm">
        {item.contactPerson && (
          <div className="font-medium text-gray-800 dark:text-gray-100">
            {item.contactPerson}
          </div>
        )}
        <div className="flex space-x-2 text-[11px] text-gray-500 font-mono mt-0.5 dark:text-gray-400">
          <span>{item.phone || "No phone"}</span>
          {item.email && <span>• {item.email}</span>}
        </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col h-full animate-in fade-in duration-300">
      {/* Sub-pages / Sub-tabs selector for Contacts (All, Staff, Customers, Vendors, Partners) */}
      <div className="flex border-b border-gray-150 bg-gray-50/50 px-4 pt-2 dark:bg-gray-800/20 dark:border-gray-800">
        {[
          { id: "all", label: "All Contacts" },
          { id: "staff", label: "Staff" },
          { id: "customers", label: "Customers" },
          { id: "vendors", label: "Vendors" },
          { id: "partners", label: "Partners" },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setSubTab(tab.id as any)}
            className={`px-5 py-2.5 text-xs font-bold transition-all relative whitespace-nowrap mr-2 rounded-t-lg ${subTab === tab.id ? "text-blue-600 bg-white dark:text-blue-400 dark:bg-gray-700" : "text-gray-500 hover:text-gray-700 dark:text-gray-400"}`}
          >
            {tab.label}
            {subTab === tab.id && (
              <div className="absolute bottom-0 left-0 right-0 h-1 bg-blue-600"></div>
            )}
          </button>
        ))}
      </div>

      {/* Sub-tab Renders */}
      {subTab === "customers" && (
        <CustomersTab data={customers} onSave={saveCustomers} />
      )}
      {subTab === "vendors" && (
        <VendorsTab data={vendors} onSave={saveVendors} />
      )}
      {subTab === "partners" && (
        <PartnersTab data={partners} onSave={savePartners} />
      )}

      {subTab === "all" && <AllContactsTab 
                        searchTerm={searchTerm} 
                        setSearchTerm={setSearchTerm} 
                        allContactsCombined={allContactsCombined} 
                        filteredAllContacts={filteredAllContacts} 
                        setIsModalOpen={setIsModalOpen} 
                        setEditingId={setEditingId} 
                        setFormData={setFormData}
                        setDeleteConfirmation={setDeleteConfirmation}
                        renderClassificationBadge={renderClassificationBadge}
                        renderDetailsCell={renderDetailsCell} 
                     />}
{subTab === "staff" && <StaffTab onSave={onSave} searchTerm={searchTerm} 
                        setSearchTerm={setSearchTerm} 
                        data={data} 
                        filteredStaffData={filteredStaffData} 
                        setIsModalOpen={setIsModalOpen} 
                        setEditingId={setEditingId} 
                        setFormData={setFormData}
                        setDeleteConfirmation={setDeleteConfirmation}
                        renderClassificationBadge={renderClassificationBadge}
                        renderDetailsCell={renderDetailsCell} 
                     />}
{isModalOpen && <ContactFormModal 
                        isOpen={isModalOpen}
                        onClose={() => { setIsModalOpen(false); setEditingId(null); setFormData({}); }}
                        formData={formData}
                        setFormData={setFormData}
                        editingId={editingId}
                        handleSaveUnified={handleSaveUnified}
                        handleFileUpload={handleFileUpload}
                        setExpandedSection={setExpandedSection}
                        expandedSection={expandedSection}
                        formSettings={formSettings} data={data} partyMasters={partyMasters} getAutoGeneratedCode={getAutoGeneratedCode}
                     />}{/* Unified Delete Confirmation Modal */}
      {deleteConfirmation?.isOpen && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl p-6 w-full max-w-sm text-center shadow-2xl animate-in zoom-in-95 dark:bg-gray-800">
            <div className="w-16 h-16 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-4 text-red-500">
              <DeleteIcon className="text-3xl" />
            </div>
            <h2 className="font-bold text-xl mb-2 text-gray-900 dark:text-white">
              Delete Contact?
            </h2>
            <p className="text-gray-500 mb-6 text-sm dark:text-gray-400">
              Are you sure you want to delete "{deleteConfirmation.name}" (
              {deleteConfirmation.type})?
            </p>
            <div className="flex space-x-3">
              <button
                onClick={() => setDeleteConfirmation(null)}
                className="flex-1 py-3 bg-white border border-gray-200 text-gray-700 font-bold rounded-xl hover:bg-gray-50 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-200 hover:dark:bg-gray-700 transition"
              >
                Cancel
              </button>
              <button
                onClick={confirmDeleteUnified}
                className="flex-1 py-3 bg-red-600 text-white font-bold rounded-xl hover:bg-red-700 shadow-md shadow-red-200 transition"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
