import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const AddressSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Address */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "address" ? null : "address",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "address"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📍 Address Details")}</span>
                        {expandedSection === "address" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "address" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              {/* Street Address */}
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label text-xs">{t("Street Address")}</label>
                                <input
                                  type="text"
                                  value={formData.streetAddress || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      streetAddress: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("Street name, building etc.")}
                                />
                              </div>

                              {/* District */}
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("District")}</label>
                                <input
                                  type="text"
                                  value={formData.district || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      district: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Bandra West")}
                                />
                              </div>

                              {/* City */}
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("City")}</label>
                                <input
                                  type="text"
                                  value={formData.city || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      city: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Mumbai, New Delhi")}
                                />
                              </div>

                              {/* State */}
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("State")}</label>
                                <select
                                  value={formData.state || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      state: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select State...")}</option>
                                  <option value="Andhra Pradesh">{t("Andhra Pradesh")}</option>
                                  <option value="Arunachal Pradesh">{t("Arunachal Pradesh")}</option>
                                  <option value="Assam">{t("Assam")}</option>
                                  <option value="Bihar">{t("Bihar")}</option>
                                  <option value="Chhattisgarh">{t("Chhattisgarh")}</option>
                                  <option value="Goa">{t("Goa")}</option>
                                  <option value="Gujarat">{t("Gujarat")}</option>
                                  <option value="Haryana">{t("Haryana")}</option>
                                  <option value="Himachal Pradesh">{t("Himachal Pradesh")}</option>
                                  <option value="Jharkhand">{t("Jharkhand")}</option>
                                  <option value="Karnataka">{t("Karnataka")}</option>
                                  <option value="Kerala">{t("Kerala")}</option>
                                  <option value="Madhya Pradesh">{t("Madhya Pradesh")}</option>
                                  <option value="Maharashtra">{t("Maharashtra")}</option>
                                  <option value="Manipur">{t("Manipur")}</option>
                                  <option value="Meghalaya">{t("Meghalaya")}</option>
                                  <option value="Mizoram">{t("Mizoram")}</option>
                                  <option value="Nagaland">{t("Nagaland")}</option>
                                  <option value="Odisha">{t("Odisha")}</option>
                                  <option value="Punjab">{t("Punjab")}</option>
                                  <option value="Rajasthan">{t("Rajasthan")}</option>
                                  <option value="Sikkim">{t("Sikkim")}</option>
                                  <option value="Tamil Nadu">{t("Tamil Nadu")}</option>
                                  <option value="Telangana">{t("Telangana")}</option>
                                  <option value="Tripura">{t("Tripura")}</option>
                                  <option value="Uttar Pradesh">{t("Uttar Pradesh")}</option>
                                  <option value="Uttarakhand">{t("Uttarakhand")}</option>
                                  <option value="West Bengal">{t("West Bengal")}</option>
                                  <option value="Andaman and Nicobar Islands">{t("Andaman and Nicobar Islands")}</option>
                                  <option value="Chandigarh">{t("Chandigarh")}</option>
                                  <option value="Dadra and Nagar Haveli and Daman and Diu">{t("Dadra and Nagar Haveli and Daman and Diu")}</option>
                                  <option value="Delhi">{t("Delhi")}</option>
                                  <option value="Jammu and Kashmir">{t("Jammu and Kashmir")}</option>
                                  <option value="Ladakh">{t("Ladakh")}</option>
                                  <option value="Lakshadweep">{t("Lakshadweep")}</option>
                                  <option value="Puducherry">{t("Puducherry")}</option>
                                </select>
                              </div>

                              {/* Country */}
                              <div className="form-field-wrapper col-span-1 font-sans">
                                <label className="form-label text-xs font-sans">{t("Country")}</label>
                                <select
                                  value={formData.country || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      country: e.target.value,
                                    })
                                  }
                                  className="form-input font-sans"
                                >
                                  <option value="">{t("Select Country...")}</option>
                                  <option value="India">{t("India")}</option>
                                </select>
                              </div>

                              {/* Zip Code */}
                              <div className="form-field-wrapper col-span-1 font-sans">
                                <label className="form-label text-xs font-sans">{t("Zip Code")}</label>
                                <input
                                  type="text"
                                  value={formData.zipCode || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      zipCode: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 400050")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1 md:col-span-2 mt-4 pt-4 border-t border-slate-100 dark:border-slate-800">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-4 gap-2">
                                  <label className="form-label text-xs font-bold text-gray-600 dark:text-gray-300 mb-0">{t("Permanent Address")}</label>
                                  <button
                                    type="button"
                                    onClick={() => {
                                      const isSame = 
                                        formData.streetAddress === formData.permStreetAddress &&
                                        formData.district === formData.permDistrict &&
                                        formData.city === formData.permCity &&
                                        formData.state === formData.permState &&
                                        formData.country === formData.permCountry &&
                                        formData.zipCode === formData.permZipCode;
                                      
                                      if (isSame) {
                                        // Uncheck -> clear perm address
                                        setFormData({
                                          ...formData,
                                          permStreetAddress: "",
                                          permDistrict: "",
                                          permCity: "",
                                          permState: "",
                                          permCountry: "India",
                                          permZipCode: "",
                                        });
                                      } else {
                                        // Check -> copy local to perm
                                        setFormData({
                                          ...formData,
                                          permStreetAddress: formData.streetAddress,
                                          permDistrict: formData.district,
                                          permCity: formData.city,
                                          permState: formData.state,
                                          permCountry: formData.country,
                                          permZipCode: formData.zipCode,
                                        });
                                      }
                                    }}
                                    className="text-[10px] sm:text-xs bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-300 px-3 py-1.5 rounded hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors flex items-center justify-center gap-1.5 font-medium border border-slate-200 dark:border-slate-600 shadow-sm"
                                  >
                                    <div className="w-3.5 h-3.5 bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-500 rounded-sm flex items-center justify-center shrink-0">
                                      {(
                                        formData.streetAddress === formData.permStreetAddress &&
                                        formData.district === formData.permDistrict &&
                                        formData.city === formData.permCity &&
                                        formData.state === formData.permState &&
                                        formData.country === formData.permCountry &&
                                        formData.zipCode === formData.permZipCode
                                      ) && (
                                        <svg className="w-2.5 h-2.5 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                                          <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                                        </svg>
                                      )}
                                    </div>
                                    Same as Local Address
                                  </button>
                                </div>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                  <div className="form-field-wrapper col-span-1 md:col-span-2">
                                    <label className="form-label text-xs">{t("Street Address")}</label>
                                    <input
                                      type="text"
                                      value={formData.permStreetAddress || ""}
                                      onChange={(e) => setFormData({ ...formData, permStreetAddress: e.target.value })}
                                      className="form-input"
                                      placeholder={t("Street name, building etc.")}
                                    />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("District")}</label>
                                    <input
                                      type="text"
                                      value={formData.permDistrict || ""}
                                      onChange={(e) => setFormData({ ...formData, permDistrict: e.target.value })}
                                      className="form-input"
                                      placeholder={t("e.g. Bandra West")}
                                    />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("City")}</label>
                                    <input
                                      type="text"
                                      value={formData.permCity || ""}
                                      onChange={(e) => setFormData({ ...formData, permCity: e.target.value })}
                                      className="form-input"
                                      placeholder={t("e.g. Mumbai, New Delhi")}
                                    />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("State")}</label>
                                    <select
                                      value={formData.permState || ""}
                                      onChange={(e) => setFormData({ ...formData, permState: e.target.value })}
                                      className="form-input"
                                    >
                                      <option value="">{t("Select State...")}</option>
                                      <option value="Andhra Pradesh">{t("Andhra Pradesh")}</option>
                                      <option value="Arunachal Pradesh">{t("Arunachal Pradesh")}</option>
                                      <option value="Assam">{t("Assam")}</option>
                                      <option value="Bihar">{t("Bihar")}</option>
                                      <option value="Chhattisgarh">{t("Chhattisgarh")}</option>
                                      <option value="Goa">{t("Goa")}</option>
                                      <option value="Gujarat">{t("Gujarat")}</option>
                                      <option value="Haryana">{t("Haryana")}</option>
                                      <option value="Himachal Pradesh">{t("Himachal Pradesh")}</option>
                                      <option value="Jharkhand">{t("Jharkhand")}</option>
                                      <option value="Karnataka">{t("Karnataka")}</option>
                                      <option value="Kerala">{t("Kerala")}</option>
                                      <option value="Madhya Pradesh">{t("Madhya Pradesh")}</option>
                                      <option value="Maharashtra">{t("Maharashtra")}</option>
                                      <option value="Manipur">{t("Manipur")}</option>
                                      <option value="Meghalaya">{t("Meghalaya")}</option>
                                      <option value="Mizoram">{t("Mizoram")}</option>
                                      <option value="Nagaland">{t("Nagaland")}</option>
                                      <option value="Odisha">{t("Odisha")}</option>
                                      <option value="Punjab">{t("Punjab")}</option>
                                      <option value="Rajasthan">{t("Rajasthan")}</option>
                                      <option value="Sikkim">{t("Sikkim")}</option>
                                      <option value="Tamil Nadu">{t("Tamil Nadu")}</option>
                                      <option value="Telangana">{t("Telangana")}</option>
                                      <option value="Tripura">{t("Tripura")}</option>
                                      <option value="Uttar Pradesh">{t("Uttar Pradesh")}</option>
                                      <option value="Uttarakhand">{t("Uttarakhand")}</option>
                                      <option value="West Bengal">{t("West Bengal")}</option>
                                      <option value="Andaman and Nicobar Islands">{t("Andaman and Nicobar Islands")}</option>
                                      <option value="Chandigarh">{t("Chandigarh")}</option>
                                      <option value="Dadra and Nagar Haveli and Daman and Diu">{t("Dadra and Nagar Haveli and Daman and Diu")}</option>
                                      <option value="Delhi">{t("Delhi")}</option>
                                      <option value="Jammu and Kashmir">{t("Jammu and Kashmir")}</option>
                                      <option value="Ladakh">{t("Ladakh")}</option>
                                      <option value="Lakshadweep">{t("Lakshadweep")}</option>
                                      <option value="Puducherry">{t("Puducherry")}</option>
                                    </select>
                                  </div>
                                  <div className="form-field-wrapper col-span-1 font-sans">
                                    <label className="form-label text-xs font-sans">{t("Country")}</label>
                                    <select
                                      value={formData.permCountry || ""}
                                      onChange={(e) => setFormData({ ...formData, permCountry: e.target.value })}
                                      className="form-input font-sans"
                                    >
                                      <option value="">{t("Select Country...")}</option>
                                      <option value="India">{t("India")}</option>
                                    </select>
                                  </div>
                                  <div className="form-field-wrapper col-span-1 font-sans">
                                    <label className="form-label text-xs font-sans">{t("Zip Code")}</label>
                                    <input
                                      type="text"
                                      value={formData.permZipCode || ""}
                                      onChange={(e) => setFormData({ ...formData, permZipCode: e.target.value })}
                                      className="form-input font-mono"
                                      placeholder={t("e.g. 400050")}
                                    />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
