import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const AddressInfoSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Address Info */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "biz_address"
                              ? null
                              : "biz_address",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "biz_address"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📍 Address Details")}</span>
                        {expandedSection === "biz_address" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "biz_address" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label dark:text-gray-400">{t("Address Line")}</label>
                                <input
                                  type="text"
                                  value={formData.address || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      address: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none"
                                  placeholder={t("Street info...")}
                                />
                              </div>
                              <div className="form-field-wrapper">
                                <label className="form-label dark:text-gray-400">{t("City")}</label>
                                <input
                                  type="text"
                                  value={formData.city || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      city: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none"
                                />
                              </div>
                              <div className="form-field-wrapper">
                                <label className="form-label dark:text-gray-400">{t("State / Region")}</label>
                                <input
                                  type="text"
                                  value={formData.state || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      state: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none"
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label dark:text-gray-400">{t("Pincode / ZIP")}</label>
                                <input
                                  type="text"
                                  value={formData.pincode || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      pincode: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none font-mono"
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
