import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const AssetsEquipmentSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Assets & Equipment */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "assets_info" ? null : "assets_info",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "assets_info"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("💻 Assets & Equipment")}</span>
                        {expandedSection === "assets_info" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "assets_info" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Assigned Laptop / PC")}</label>
                                <input
                                  type="text"
                                  value={formData.assignedLaptop || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      assignedLaptop: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. MacBook Pro M2")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Assigned Mobile / SIM")}</label>
                                <input
                                  type="text"
                                  value={formData.assignedMobile || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      assignedMobile: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. iPhone 13")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label text-xs">{t("Other Assigned Assets")}</label>
                                <textarea
                                  value={formData.assignedOtherAssets || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      assignedOtherAssets: e.target.value,
                                    })
                                  }
                                  className="form-input min-h-[60px] resize-y"
                                  placeholder={t("e.g. ID Card, Office Keys...")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
