import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const BankDetailSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Bank Detail */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "bank_detail" ? null : "bank_detail",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "bank_detail"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("🏦 Bank Details")}</span>
                        {expandedSection === "bank_detail" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "bank_detail" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Bank Name")}</label>
                                <select
                                  value={formData.bankName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      bankName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Bank...")}</option>
                                  <option value="State Bank of India (SBI)">{t("State Bank of India (SBI)")}</option>
                                  <option value="Punjab National Bank (PNB)">{t("Punjab National Bank (PNB)")}</option>
                                  <option value="Bank of Baroda (BOB)">{t("Bank of Baroda (BOB)")}</option>
                                  <option value="Canara Bank">{t("Canara Bank")}</option>
                                  <option value="Union Bank of India">{t("Union Bank of India")}</option>
                                  <option value="Bank of India (BOI)">{t("Bank of India (BOI)")}</option>
                                  <option value="Indian Bank">{t("Indian Bank")}</option>
                                  <option value="Central Bank of India">{t("Central Bank of India")}</option>
                                  <option value="Indian Overseas Bank (IOB)">{t("Indian Overseas Bank (IOB)")}</option>
                                  <option value="UCO Bank">{t("UCO Bank")}</option>
                                  <option value="Bank of Maharashtra">{t("Bank of Maharashtra")}</option>
                                  <option value="Punjab & Sind Bank">{t("Punjab & Sind Bank")}</option>
                                  <option value="HDFC Bank">{t("HDFC Bank")}</option>
                                  <option value="ICICI Bank">{t("ICICI Bank")}</option>
                                  <option value="Axis Bank">{t("Axis Bank")}</option>
                                  <option value="Kotak Mahindra Bank">{t("Kotak Mahindra Bank")}</option>
                                  <option value="IndusInd Bank">{t("IndusInd Bank")}</option>
                                  <option value="Yes Bank">{t("Yes Bank")}</option>
                                  <option value="IDFC First Bank">{t("IDFC First Bank")}</option>
                                  <option value="Federal Bank">{t("Federal Bank")}</option>
                                  <option value="South Indian Bank">{t("South Indian Bank")}</option>
                                  <option value="Karur Vysya Bank">{t("Karur Vysya Bank")}</option>
                                  <option value="City Union Bank">{t("City Union Bank")}</option>
                                  <option value="Bandhan Bank">{t("Bandhan Bank")}</option>
                                  <option value="RBL Bank">{t("RBL Bank")}</option>
                                  <option value="Jammu & Kashmir Bank">{t("Jammu & Kashmir Bank")}</option>
                                  <option value="Karnataka Bank">{t("Karnataka Bank")}</option>
                                  <option value="Tamilnad Mercantile Bank">{t("Tamilnad Mercantile Bank")}</option>
                                  <option value="CSB Bank">{t("CSB Bank")}</option>
                                  <option value="Dhanlaxmi Bank">{t("Dhanlaxmi Bank")}</option>
                                  <option value="Nainital Bank">{t("Nainital Bank")}</option>
                                  <option value="Standard Chartered Bank">{t("Standard Chartered Bank")}</option>
                                  <option value="Citibank">{t("Citibank")}</option>
                                  <option value="HSBC">{t("HSBC")}</option>
                                  <option value="Deutsche Bank">{t("Deutsche Bank")}</option>
                                  <option value="Barclays Bank">{t("Barclays Bank")}</option>
                                  <option value="Other Bank">{t("Other Bank")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Account Number")}</label>
                                <input
                                  type="text"
                                  value={formData.bankAccountNumber || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      bankAccountNumber: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 50100234...")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("IFSC Code")}</label>
                                <input
                                  type="text"
                                  value={formData.bankIfscCode || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      bankIfscCode: e.target.value.toUpperCase(),
                                    })
                                  }
                                  className="form-input font-mono uppercase"
                                  placeholder={t("e.g. HDFC0001234")}
                                  maxLength={11}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Branch Name")}</label>
                                <input
                                  type="text"
                                  value={formData.bankBranch || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      bankBranch: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Connaught Place")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
