import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const BusinessProfileSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Business Profile */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "biz_profile"
                              ? null
                              : "biz_profile",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "biz_profile"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("💼 Business Profile")}</span>
                        {expandedSection === "biz_profile" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "biz_profile" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label">{t("Description / Notes")}</label>
                                <input
                                  type="text"
                                  value={
                                    formData.description || formData.notes || ""
                                  }
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      description: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none"
                                  placeholder={t("Add any description or notes...")}
                                />
                              </div>

                              <div className="form-field-wrapper">
                                <label className="form-label dark:text-gray-400">{t("GSTIN")}</label>
                                <input
                                  type="text"
                                  value={formData.gstin || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      gstin: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none font-mono"
                                  placeholder={t("e.g. 27ABCDE1234F1Z5")}
                                />
                              </div>
                              <div className="form-field-wrapper">
                                <label className="form-label dark:text-gray-400">{t("PAN Number")}</label>
                                <input
                                  type="text"
                                  value={formData.panNo || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      panNo: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none font-mono"
                                  placeholder={t("ABCDE1234F")}
                                />
                              </div>
                              <div className="form-field-wrapper font-sans col-span-1 md:col-span-2">
                                <label className="form-label dark:text-gray-400">{t("Contact Person")}</label>
                                <input
                                  type="text"
                                  value={formData.contactPerson || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      contactPerson: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none"
                                  placeholder={t("Primary Contact...")}
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label dark:text-gray-400">{t("Phone")}</label>
                                <input
                                  type="text"
                                  value={formData.phone || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      phone: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none font-mono"
                                  placeholder={t("Telephone number...")}
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label dark:text-gray-400">{t("Email Address")}</label>
                                <input
                                  type="email"
                                  value={formData.email || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      email: e.target.value,
                                    })
                                  }
                                  className="form-input animate-none font-mono"
                                  placeholder={t("example@email.com")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
