import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const ClassificationProfileInfoSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Classification & Profile Info */}
                <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                  <button
                    type="button"
                    onClick={() =>
                      setExpandedSection(
                        expandedSection === "profile_info"
                          ? null
                          : "profile_info",
                      )
                    }
                    className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                    data-open={expandedSection === "profile_info"}
                  >
                    <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📋 Profile Info")}</span>
                    {expandedSection === "profile_info" ? (
                      <ChevronUp className="w-4 h-4 text-gray-500" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-gray-500" />
                    )}
                  </button>

                  <AnimatePresence initial={false}>
                    {expandedSection === "profile_info" && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        className="overflow-hidden"
                        transition={{ duration: 0.2 }}
                      >
                        <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                          {/* Type Selector and Status - Always visible inside collapsible section */}
                          <div className="form-field-wrapper col-span-1">
                            <label className="form-label font-bold text-gray-700 dark:text-gray-300">{t("Contact Classification")}</label>
                            <select
                              id="contact-classification"
                              value={formData.unifiedType || "Staff"}
                              onChange={(e) => {
                                const uType = e.target.value as any;
                                const nextCode = getAutoGeneratedCode(
                                  uType,
                                  data,
                                  partyMasters,
                                );
                                setFormData({
                                  ...formData,
                                  unifiedType: uType,
                                  code: nextCode,
                                  contactType:
                                    uType === "Staff" ? "Internal" : undefined,
                                  type:
                                    uType === "Customer"
                                      ? "Customer"
                                      : uType === "Vendor"
                                        ? "Vendor"
                                        : uType === "Partner"
                                          ? "Both"
                                          : undefined,
                                });
                              }}
                              className="form-input"
                            >
                              <option value="Staff">{t("Staff (Internal / Contract)")}</option>
                              <option value="Customer">{t("Customer")}</option>
                              <option value="Vendor">{t("Vendor")}</option>
                              <option value="Partner">{t("Partner")}</option>
                            </select>
                          </div>

                          <div className="form-field-wrapper col-span-1">
                            <label className="form-label font-bold text-gray-700 dark:text-gray-300">{t("Status")}</label>
                            <select
                              id="contact-status"
                              value={formData.status || "Active"}
                              onChange={(e) =>
                                setFormData({
                                  ...formData,
                                  status: e.target.value,
                                })
                              }
                              className="form-input"
                            >
                              <option value="Active">{t("Active / Enable")}</option>
                              <option value="Inactive">{t("Inactive / Disable")}</option>
                            </select>
                          </div>

                          {/* Code and Name */}
                          <div className="form-field-wrapper col-span-1">
                            <label className="form-label text-xs">{t("Code *")}</label>
                            <input
                              type="text"
                              id="contact-code"
                              value={formData.code || ""}
                              onChange={(e) =>
                                setFormData({
                                  ...formData,
                                  code: e.target.value,
                                })
                              }
                              className="form-input bg-white dark:bg-gray-900 font-mono"
                              placeholder={t("Enter contact code...")}
                              autoFocus
                            />
                          </div>
                          <div className="form-field-wrapper col-span-1">
                            <label className="form-label">{t("Name *")}</label>
                            <input
                              type="text"
                              id="contact-name"
                              value={formData.name || ""}
                              onChange={(e) =>
                                setFormData({
                                  ...formData,
                                  name: e.target.value,
                                })
                              }
                              className="form-input"
                              placeholder={t("Enter contact name...")}
                            />
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
    </>
  );
};
