import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const ComplianceVerificationSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Compliance & Verification */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "compliance_info" ? null : "compliance_info",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "compliance_info"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("🛡️ Compliance & Verification")}</span>
                        {expandedSection === "compliance_info" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "compliance_info" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Police Verification")}</label>
                                <select
                                  value={formData.policeVerificationStatus || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      policeVerificationStatus: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Status...")}</option>
                                  <option value="Pending">{t("Pending")}</option>
                                  <option value="Initiated">{t("Initiated")}</option>
                                  <option value="Completed">{t("Completed")}</option>
                                  <option value="Not Required">{t("Not Required")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Background Check (BGC)")}</label>
                                <select
                                  value={formData.backgroundCheckStatus || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      backgroundCheckStatus: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select...")}</option>
                                  <option value="Pending">{t("Pending")}</option>
                                  <option value="In Progress">{t("In Progress")}</option>
                                  <option value="Cleared">{t("Cleared")}</option>
                                  <option value="Not Required">{t("Not Required")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Medical Fitness")}</label>
                                <select
                                  value={formData.medicalFitnessStatus || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      medicalFitnessStatus: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select...")}</option>
                                  <option value="Pending">{t("Pending")}</option>
                                  <option value="Fit">{t("Fit")}</option>
                                  <option value="Unfit">{t("Unfit")}</option>
                                </select>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
