import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const ContactModeofContactSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Contact Mode of Contact */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "contact_mode"
                              ? null
                              : "contact_mode",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "contact_mode"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📞 Contact Info")}</span>
                        {expandedSection === "contact_mode" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "contact_mode" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Email Address")}</label>
                                <input
                                  type="email"
                                  id="staff-email"
                                  value={formData.email || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      email: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. name@bharatbook.com")}
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Phone / Mobile Number")}</label>
                                <input
                                  type="text"
                                  id="staff-phone"
                                  value={formData.phone || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      phone: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 9811223344")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] text-gray-500 font-semibold">{t("Work Email Address")}</label>
                                <input
                                  type="email"
                                  value={formData.workEmail || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      workEmail: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. work@company.com")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] text-gray-500 font-semibold">{t("Work Phone Number")}</label>
                                <input
                                  type="text"
                                  value={formData.workPhone || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      workPhone: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 022-12345678")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1 md:col-span-2 mt-4 pt-4 border-t border-slate-100 dark:border-slate-700">
                                <h4 className="text-xs font-bold text-slate-800 dark:text-gray-200 mb-4">{t("Emergency / Alternate Contact")}</h4>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Alternative Contact Number")}</label>
                                <input
                                  type="text"
                                  id="staff-alternate-phone"
                                  value={formData.alternatePhone || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      alternatePhone: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 9822334455")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Alternative WhatsApp Number")}</label>
                                <input
                                  type="text"
                                  id="staff-alternate-whatsapp"
                                  value={formData.alternateWhatsapp || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      alternateWhatsapp: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 9822334455")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Name of that person of alternative")}</label>
                                <input
                                  type="text"
                                  value={formData.alternateName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      alternateName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("Contact Person Name")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs font-semibold text-gray-500 dark:text-gray-400">{t("Relation of Alternate Contact")}</label>
                                <select
                                  id="staff-alternate-relation"
                                  value={formData.alternateRelation || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      alternateRelation: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Relation...")}</option>
                                  <option value="Father">{t("Father")}</option>
                                  <option value="Mother">{t("Mother")}</option>
                                  <option value="Husband">{t("Husband")}</option>
                                  <option value="Wife">{t("Wife")}</option>
                                  <option value="Brother">{t("Brother")}</option>
                                  <option value="Sister">{t("Sister")}</option>
                                  <option value="Son">{t("Son")}</option>
                                  <option value="Daughter">{t("Daughter")}</option>
                                  <option value="Guardian">{t("Guardian")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
