import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const DocumentsProofsSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Documents & Proofs */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "document_upload" ? null : "document_upload",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "document_upload"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📄 Document Upload")}</span>
                        {expandedSection === "document_upload" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "document_upload" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Aadhaar Card")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentAadhaarUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentAadhaarUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("PAN Card")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentPanUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentPanUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>
                              
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Voter ID Card")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentVoterIdUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentVoterIdUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Driving License")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentDrivingLicenseUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentDrivingLicenseUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Passport")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentPassportUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentPassportUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Resume")}</label>
                                <input
                                  type="file"
                                  accept="application/pdf,.doc,.docx"
                                  onChange={(e) => handleFileUpload(e, "documentResumeUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentResumeUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>
                              
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Matriculation (10th) Marksheet")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentMatricMarksheetUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentMatricMarksheetUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Intermediate / Diploma Marksheet")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentIntermediateMarksheetUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentIntermediateMarksheetUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Highest Qual. Marksheet / Degree")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentMarksheetUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentMarksheetUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>
                              
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Relieving / Experience Letter")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentExperienceLetterUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentExperienceLetterUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>
                              
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Cancelled Cheque / Bank Passbook")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentBankProofUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentBankProofUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Other Certificates")}</label>
                                <input
                                  type="file"
                                  accept="image/*,application/pdf"
                                  onChange={(e) => handleFileUpload(e, "documentOtherUrl")}
                                  className="form-input !p-1.5 text-xs file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-300"
                                />
                                {formData.documentOtherUrl && (
                                  <div className="mt-2 text-[10px] text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1">
                                    <span className="w-2 h-2 rounded-full bg-emerald-500" />{t("Document Uploaded")}</div>
                                )}
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
