import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const EducationQualificationSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Education & Qualification */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "education" ? null : "education",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "education"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("🎓 Education & Qualification")}</span>
                        {expandedSection === "education" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "education" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 flex flex-col gap-6">
                              {/* Matriculation (10th) */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Matriculation (10th)")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("School Name")}</label>
                                    <input type="text" value={formData.matriculationSchool || ""} onChange={(e) => setFormData({ ...formData, matriculationSchool: e.target.value })} className="form-input" placeholder={t("e.g. DPS")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Board/University Name")}</label>
                                    <input type="text" value={formData.matriculationBoard || ""} onChange={(e) => setFormData({ ...formData, matriculationBoard: e.target.value })} className="form-input" placeholder={t("e.g. CBSE")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Year of Passing")}</label>
                                    <input type="number" value={formData.matriculationYear || ""} onChange={(e) => setFormData({ ...formData, matriculationYear: e.target.value })} className="form-input" placeholder={t("e.g. 2012")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Percentage")}</label>
                                    <input type="text" value={formData.matriculationPercentage || ""} onChange={(e) => setFormData({ ...formData, matriculationPercentage: e.target.value })} className="form-input" placeholder={t("e.g. 85%")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("CGPA")}</label>
                                    <input type="text" value={formData.matriculationCGPA || ""} onChange={(e) => setFormData({ ...formData, matriculationCGPA: e.target.value })} className="form-input" placeholder={t("e.g. 9.0")} />
                                  </div>
                                </div>
                              </div>

                              {/* Intermediate (12th) */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Intermediate (12th)")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Stream")}</label>
                                    <select value={formData.intermediateStream || ""} onChange={(e) => setFormData({ ...formData, intermediateStream: e.target.value })} className="form-input">
                                      <option value="">{t("Select Stream...")}</option>
                                      <option value="Arts">{t("Arts")}</option>
                                      <option value="Science">{t("Science")}</option>
                                      <option value="Commerce">{t("Commerce")}</option>
                                      <option value="Other">{t("Other")}</option>
                                    </select>
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("School/College Name")}</label>
                                    <input type="text" value={formData.intermediateSchool || ""} onChange={(e) => setFormData({ ...formData, intermediateSchool: e.target.value })} className="form-input" placeholder={t("e.g. DPS")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Board/University Name")}</label>
                                    <input type="text" value={formData.intermediateBoard || ""} onChange={(e) => setFormData({ ...formData, intermediateBoard: e.target.value })} className="form-input" placeholder={t("e.g. CBSE")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Year of Passing")}</label>
                                    <input type="number" value={formData.intermediateYear || ""} onChange={(e) => setFormData({ ...formData, intermediateYear: e.target.value })} className="form-input" placeholder={t("e.g. 2014")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Percentage")}</label>
                                    <input type="text" value={formData.intermediatePercentage || ""} onChange={(e) => setFormData({ ...formData, intermediatePercentage: e.target.value })} className="form-input" placeholder={t("e.g. 80%")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("CGPA")}</label>
                                    <input type="text" value={formData.intermediateCGPA || ""} onChange={(e) => setFormData({ ...formData, intermediateCGPA: e.target.value })} className="form-input" placeholder={t("e.g. 8.5")} />
                                  </div>
                                </div>
                              </div>

                              {/* Graduation */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Graduation")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-7 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Degree Name")}</label>
                                    <select value={formData.graduationDegreeName || ""} onChange={(e) => setFormData({ ...formData, graduationDegreeName: e.target.value })} className="form-input">
                                      <option value="">{t("Select Degree...")}</option>
                                      <option value="BA">{t("BA")}</option>
                                      <option value="B.Sc">{t("B.Sc")}</option>
                                      <option value="B.Com">{t("B.Com")}</option>
                                      <option value="B.Tech">{t("B.Tech")}</option>
                                      <option value="BBA">{t("BBA")}</option>
                                      <option value="BCA">{t("BCA")}</option>
                                      <option value="Other">{t("Other")}</option>
                                    </select>
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Stream/Specialization")}</label>
                                    <input type="text" value={formData.graduationStream || ""} onChange={(e) => setFormData({ ...formData, graduationStream: e.target.value })} className="form-input" placeholder={t("e.g. IT")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("College Name")}</label>
                                    <input type="text" value={formData.graduationCollege || ""} onChange={(e) => setFormData({ ...formData, graduationCollege: e.target.value })} className="form-input" placeholder={t("e.g. MIT")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("University Name")}</label>
                                    <input type="text" value={formData.graduationUniversity || ""} onChange={(e) => setFormData({ ...formData, graduationUniversity: e.target.value })} className="form-input" placeholder={t("e.g. Pune Univ")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Year of Passing")}</label>
                                    <input type="number" value={formData.graduationYear || ""} onChange={(e) => setFormData({ ...formData, graduationYear: e.target.value })} className="form-input" placeholder={t("e.g. 2018")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Percentage")}</label>
                                    <input type="text" value={formData.graduationPercentage || ""} onChange={(e) => setFormData({ ...formData, graduationPercentage: e.target.value })} className="form-input" placeholder={t("e.g. 75%")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("CGPA")}</label>
                                    <input type="text" value={formData.graduationCGPA || ""} onChange={(e) => setFormData({ ...formData, graduationCGPA: e.target.value })} className="form-input" placeholder={t("e.g. 8.0")} />
                                  </div>
                                </div>
                              </div>

                              {/* Post Graduation */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Post Graduation")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-7 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Degree Name")}</label>
                                    <select value={formData.postGraduationDegreeName || ""} onChange={(e) => setFormData({ ...formData, postGraduationDegreeName: e.target.value })} className="form-input">
                                      <option value="">{t("Select Degree...")}</option>
                                      <option value="MA">{t("MA")}</option>
                                      <option value="M.Sc">{t("M.Sc")}</option>
                                      <option value="M.Com">{t("M.Com")}</option>
                                      <option value="M.Tech">{t("M.Tech")}</option>
                                      <option value="MBA">{t("MBA")}</option>
                                      <option value="MCA">{t("MCA")}</option>
                                      <option value="Other">{t("Other")}</option>
                                    </select>
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Stream/Specialization")}</label>
                                    <input type="text" value={formData.postGraduationStream || ""} onChange={(e) => setFormData({ ...formData, postGraduationStream: e.target.value })} className="form-input" placeholder={t("e.g. Finance")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("College Name")}</label>
                                    <input type="text" value={formData.postGraduationCollege || ""} onChange={(e) => setFormData({ ...formData, postGraduationCollege: e.target.value })} className="form-input" />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("University Name")}</label>
                                    <input type="text" value={formData.postGraduationUniversity || ""} onChange={(e) => setFormData({ ...formData, postGraduationUniversity: e.target.value })} className="form-input" />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Year of Passing")}</label>
                                    <input type="number" value={formData.postGraduationYear || ""} onChange={(e) => setFormData({ ...formData, postGraduationYear: e.target.value })} className="form-input" />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Percentage")}</label>
                                    <input type="text" value={formData.postGraduationPercentage || ""} onChange={(e) => setFormData({ ...formData, postGraduationPercentage: e.target.value })} className="form-input" />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("CGPA")}</label>
                                    <input type="text" value={formData.postGraduationCGPA || ""} onChange={(e) => setFormData({ ...formData, postGraduationCGPA: e.target.value })} className="form-input" />
                                  </div>
                                </div>
                              </div>

                              {/* Diploma */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Diploma")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Course Name")}</label>
                                    <input type="text" value={formData.diplomaCourse || ""} onChange={(e) => setFormData({ ...formData, diplomaCourse: e.target.value })} className="form-input" placeholder={t("e.g. Diploma in IT")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Institute/College")}</label>
                                    <input type="text" value={formData.diplomaCollege || ""} onChange={(e) => setFormData({ ...formData, diplomaCollege: e.target.value })} className="form-input" placeholder={t("e.g. Govt Polytechnic")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Board/University Name")}</label>
                                    <input type="text" value={formData.diplomaUniversity || ""} onChange={(e) => setFormData({ ...formData, diplomaUniversity: e.target.value })} className="form-input" placeholder={t("e.g. State Board")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Year of Passing")}</label>
                                    <input type="number" value={formData.diplomaYear || ""} onChange={(e) => setFormData({ ...formData, diplomaYear: e.target.value })} className="form-input" placeholder={t("e.g. 2016")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Percentage")}</label>
                                    <input type="text" value={formData.diplomaPercentage || ""} onChange={(e) => setFormData({ ...formData, diplomaPercentage: e.target.value })} className="form-input" placeholder={t("e.g. 80%")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("CGPA")}</label>
                                    <input type="text" value={formData.diplomaCGPA || ""} onChange={(e) => setFormData({ ...formData, diplomaCGPA: e.target.value })} className="form-input" placeholder={t("e.g. 8.5")} />
                                  </div>
                                </div>
                              </div>

                              {/* Certifications */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Certifications")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Certification Course 1")}</label>
                                    <input type="text" value={formData.certification1 || ""} onChange={(e) => setFormData({ ...formData, certification1: e.target.value })} className="form-input" placeholder={t("e.g. AWS Solutions Architect")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Certification Course 2")}</label>
                                    <input type="text" value={formData.certification2 || ""} onChange={(e) => setFormData({ ...formData, certification2: e.target.value })} className="form-input" placeholder={t("e.g. Google Cloud Developer")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Certification Course 3")}</label>
                                    <input type="text" value={formData.certification3 || ""} onChange={(e) => setFormData({ ...formData, certification3: e.target.value })} className="form-input" placeholder={t("e.g. Certified Scrum Master")} />
                                  </div>
                                </div>
                              </div>

                              {/* Highest Qualification */}
                              <div>
                                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-3 border-b border-gray-100 dark:border-gray-700 pb-2">{t("Highest Qualification Details")}</h3>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Highest Qualification")}</label>
                                    <select value={formData.highestQualification || ""} onChange={(e) => setFormData({ ...formData, highestQualification: e.target.value })} className="form-input">
                                      <option value="">{t("Select Qualification...")}</option>
                                      <option value="10th">{t("10th (Matriculation)")}</option>
                                      <option value="12th">{t("12th (Intermediate)")}</option>
                                      <option value="Diploma">{t("Diploma")}</option>
                                      <option value="Graduate">{t("Graduate")}</option>
                                      <option value="Post Graduate">{t("Post Graduate")}</option>
                                      <option value="Doctorate">{t("Doctorate")}</option>
                                      <option value="Other">{t("Other")}</option>
                                    </select>
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("Percentage")}</label>
                                    <input type="text" value={formData.highestQualificationPercentage || ""} onChange={(e) => setFormData({ ...formData, highestQualificationPercentage: e.target.value })} className="form-input" placeholder={t("e.g. 85%")} />
                                  </div>
                                  <div className="form-field-wrapper col-span-1">
                                    <label className="form-label text-xs">{t("CGPA")}</label>
                                    <input type="text" value={formData.highestQualificationCGPA || ""} onChange={(e) => setFormData({ ...formData, highestQualificationCGPA: e.target.value })} className="form-input" placeholder={t("e.g. 8.5")} />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
