import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const EmploymentStatusSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Employment Status */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "employment_status" ? null : "employment_status",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "employment_status"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("💼 Employment Status")}</span>
                        {expandedSection === "employment_status" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "employment_status" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Currently Working?")}</label>
                                <select
                                  id="staff-status"
                                  value={
                                    formData.status === "Inactive" ||
                                    formData.status === "Resigned"
                                      ? "Inactive"
                                      : "Active"
                                  }
                                  onChange={(e) => {
                                    const val = e.target.value;
                                    setFormData({
                                      ...formData,
                                      status: val,
                                      resignationDate:
                                        val === "Active"
                                          ? ""
                                          : formData.resignationDate || "",
                                      resignationReason:
                                        val === "Active"
                                          ? ""
                                          : formData.resignationReason || "",
                                      resignationDescription:
                                        val === "Active"
                                          ? ""
                                          : formData.resignationDescription || "",
                                    });
                                  }}
                                  className="form-input font-semibold"
                                >
                                  <option value="Active">{t("Yes, Currently Working")}</option>
                                  <option value="Inactive">{t("No, Resigned / Left")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Date of Joining")}</label>
                                <input
                                  type="date"
                                  id="staff-joining-date"
                                  value={formData.dateOfJoining || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      dateOfJoining: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1 animate-in fade-in duration-300">
                                <label className={`form-label text-xs font-bold ${formData.status === "Inactive" || formData.status === "Resigned" ? "text-rose-600 dark:text-rose-400" : "text-gray-500"}`}>{t("Date of Resigning")}</label>
                                <input
                                  type="date"
                                  value={formData.resignationDate || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      resignationDate: e.target.value,
                                    })
                                  }
                                  disabled={!(formData.status === "Inactive" || formData.status === "Resigned")}
                                  className="form-input disabled:opacity-50 disabled:cursor-not-allowed font-mono disabled:border-gray-200 dark:disabled:border-gray-800 focus:border-rose-500"
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1 animate-in fade-in duration-300">
                                <label className={`form-label text-xs font-bold ${formData.status === "Inactive" || formData.status === "Resigned" ? "text-rose-600 dark:text-rose-400" : "text-gray-500"}`}>{t("Reason for Resigning")}</label>
                                <select
                                  value={formData.resignationReason || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      resignationReason: e.target.value,
                                    })
                                  }
                                  disabled={!(formData.status === "Inactive" || formData.status === "Resigned")}
                                  className="form-input disabled:opacity-50 disabled:cursor-not-allowed disabled:border-gray-200 dark:disabled:border-gray-800"
                                >
                                  <option value="">{t("Select Reason...")}</option>
                                  <option value="Better Opportunity">{t("Better Opportunity")}</option>
                                  <option value="Personal Reasons">{t("Personal Reasons")}</option>
                                  <option value="Health Issues">{t("Health Issues")}</option>
                                  <option value="Relocation">{t("Relocation")}</option>
                                  <option value="Further Education">{t("Further Education")}</option>
                                  <option value="Termination">{t("Termination")}</option>
                                  <option value="Retirement">{t("Retirement")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1 md:col-span-2 animate-in fade-in duration-300">
                                <label className={`form-label text-xs font-bold ${formData.status === "Inactive" || formData.status === "Resigned" ? "text-rose-600 dark:text-rose-400" : "text-gray-500"}`}>{t("Detailed Reason / Description for Resigning")}</label>
                                <textarea
                                  value={formData.resignationDescription || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      resignationDescription: e.target.value,
                                    })
                                  }
                                  disabled={!(formData.status === "Inactive" || formData.status === "Resigned")}
                                  className="form-input min-h-[60px] resize-y disabled:opacity-50 disabled:cursor-not-allowed disabled:border-gray-200 dark:disabled:border-gray-800"
                                  placeholder={t("Provide any additional details or context about the resignation manually...")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
