import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const ExperienceDetailSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Experience Detail */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "experience" ? null : "experience",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "experience"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("💼 Experience Section")}</span>
                        {expandedSection === "experience" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "experience" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Total Experience (Years)")}</label>
                                <input type="number" value={formData.totalExperience || ""} onChange={(e) => setFormData({ ...formData, totalExperience: e.target.value })} className="form-input" placeholder={t("e.g. 5")} min="0" step="0.5" />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Relevant Experience (Years)")}</label>
                                <input type="number" value={formData.relevantExperience || ""} onChange={(e) => setFormData({ ...formData, relevantExperience: e.target.value })} className="form-input" placeholder={t("e.g. 3")} min="0" step="0.5" />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Current/Last Company Name")}</label>
                                <input type="text" value={formData.lastCompanyName || ""} onChange={(e) => setFormData({ ...formData, lastCompanyName: e.target.value })} className="form-input" placeholder={t("e.g. Tech Solutions Inc.")} />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Current/Last Designation")}</label>
                                <input type="text" value={formData.lastDesignation || ""} onChange={(e) => setFormData({ ...formData, lastDesignation: e.target.value })} className="form-input" placeholder={t("e.g. Senior Software Engineer")} />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
