import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const FamilyDetailSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Family Detail */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "family" ? null : "family",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "family"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("👨‍👩‍👧 Family Detail")}</span>
                        {expandedSection === "family" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "family" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label text-xs">{t("Father's Name")}</label>
                                <input
                                  type="text"
                                  value={formData.guardianName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      guardianName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Ramesh Kumar")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Mother's Name")}</label>
                                <input
                                  type="text"
                                  value={formData.motherName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      motherName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Sita Devi")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Husband's Name")}</label>
                                <input
                                  type="text"
                                  value={formData.husbandName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      husbandName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Shyam Sharma")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Wife's Name")}</label>
                                <input
                                  type="text"
                                  value={formData.wifeName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      wifeName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Radica Sharma")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Father's Occupation")}</label>
                                <input
                                  type="text"
                                  value={formData.fatherOccupation || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      fatherOccupation: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Retired")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Mother's Occupation")}</label>
                                <input
                                  type="text"
                                  value={formData.motherOccupation || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      motherOccupation: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Homemaker")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Husband/Wife Occupation")}</label>
                                <input
                                  type="text"
                                  value={formData.spouseOccupation || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      spouseOccupation: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Teacher")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Wedding Anniversary Date")}</label>
                                <input
                                  type="date"
                                  value={formData.anniversaryDate || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      anniversaryDate: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Is Family Residing Together?")}</label>
                                <select
                                  value={formData.isFamilyResidingTogether || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      isFamilyResidingTogether: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Option...")}</option>
                                  <option value="Yes">{t("Yes")}</option>
                                  <option value="No">{t("No")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Number of Sons")}</label>
                                <input
                                  type="number"
                                  value={formData.numberOfSons || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      numberOfSons: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. 1")}
                                  min="0"
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Number of Daughters")}</label>
                                <input
                                  type="number"
                                  value={formData.numberOfDaughters || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      numberOfDaughters: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. 1")}
                                  min="0"
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
