import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

const DEPARTMENT_DESIGNATION_MAP: Record<string, string[]> = {
  Management: ["General Manager & Operations Director", "Chief Executive Officer (CEO)", "Chief Operating Officer (COO)", "Operations Director", "Administrative Head"],
  "Marketing & Ad": ["Lead Digital Advertiser & Brand Strategist", "PPC & AdWords Marketing Consultant", "Digital Marketing Executive", "Social Media Campaign Manager", "Ad Copywriter & Content Marketer"],
  Finance: ["Finance & Taxation Manager", "Senior Accountant & Bookkeeper", "Accounts Assistant", "Auditor & Tax Consultant", "Billing & Invoice Specialist"],
  Publishing: ["Publisher Relations Specialist", "Acquisitions & Contracting Manager", "Rights & Licensing Director", "Publishing Operations Supervisor"],
  "Logistics & Supply": ["Warehouse & Inventory Supervisor", "Logistics & Distribution Coordinator", "Storekeeper", "Inventory Auditor & Quality Analyst"],
  "Customer Success": ["Senior Customer Relations Manager", "Customer Success Executive", "Technical Support Specialist", "Customer Helpdesk Coordinator"],
  "Human Resources": ["Human Resources & Payroll Lead", "HR Operations Manager", "Talent Acquisition & Onboarding executive", "Recruitment & Training Coordinator"],
  "Sales & Distribution": ["Sales & Retail Channel Manager", "Channel Distribution Specialist", "Institutional Sales Consultant", "Retail Relations Executive"],
  "Editorial & Content": ["Senior Editorial & Content Acquisition Head", "Acquisition Editor", "Senior Proofreader & Fact-checker", "Royalty Specialist"],
  "Information Technology": ["Principal System & DevOps Engineer", "Systems & Network Administrator", "IT Support Team Lead", "Database Administrator", "OCR Integration Developer"],
};
const DEPARTMENT_OPTIONS = Object.keys(DEPARTMENT_DESIGNATION_MAP);

export const GeneralCategorySection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: General Category */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "general" ? null : "general",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "general"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📂 Job Details")}</span>
                        {expandedSection === "general" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "general" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Department *")}</label>
                                <select
                                  id="staff-department"
                                  value={
                                    DEPARTMENT_OPTIONS.includes(
                                      formData.department,
                                    )
                                      ? formData.department
                                      : formData.department
                                        ? "Custom"
                                        : ""
                                  }
                                  onChange={(e) => {
                                    const val = e.target.value;
                                    if (val === "Custom") {
                                      setFormData({
                                        ...formData,
                                        department: "Custom Department",
                                        designation: "", // Clear designation when department changes
                                      });
                                    } else {
                                      setFormData({
                                        ...formData,
                                        department: val,
                                        designation: "", // Clear designation when department changes
                                      });
                                    }
                                  }}
                                  className="form-input mb-1 font-semibold text-gray-800 dark:text-gray-100 placeholder:text-gray-400"
                                >
                                  <option value="">{t("Select Department...")}</option>
                                  {DEPARTMENT_OPTIONS.map((opt) => (
                                    <option key={opt} value={opt}>
                                      {opt}
                                    </option>
                                  ))}
                                  <option value="Custom">{t("Other (Type custom)...")}</option>
                                </select>
                                {formData.department &&
                                  !DEPARTMENT_OPTIONS.includes(
                                    formData.department,
                                  ) && (
                                    <input
                                      type="text"
                                      value={
                                        formData.department ===
                                        "Custom Department"
                                          ? ""
                                          : formData.department
                                      }
                                      onChange={(e) =>
                                        setFormData({
                                          ...formData,
                                          department:
                                            e.target.value ||
                                            "Custom Department",
                                        })
                                      }
                                      className="form-input text-xs mt-1 border-dashed border-blue-300 focus:border-blue-500"
                                      placeholder={t("Type custom department...")}
                                    />
                                  )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Designation *")}</label>
                                <select
                                  id="staff-designation"
                                  value={
                                    formData.department
                                      ? (
                                          DEPARTMENT_DESIGNATION_MAP[
                                            formData.department
                                          ] || []
                                        ).includes(formData.designation)
                                        ? formData.designation
                                        : formData.designation
                                          ? "Custom"
                                          : ""
                                      : ""
                                  }
                                  onChange={(e) => {
                                    const val = e.target.value;
                                    if (val === "Custom") {
                                      setFormData({
                                        ...formData,
                                        designation: "Custom Designation",
                                      });
                                    } else {
                                      setFormData({
                                        ...formData,
                                        designation: val,
                                      });
                                    }
                                  }}
                                  disabled={!formData.department}
                                  className="form-input mb-1 font-semibold text-gray-800 dark:text-gray-100 disabled:bg-gray-100 dark:disabled:bg-gray-700 placeholder:text-gray-400"
                                >
                                  {!formData.department ? (
                                    <option value="">{t("Select a Department first...")}</option>
                                  ) : (
                                    <>
                                      <option value="">{t("Select Designation...")}</option>
                                      {(
                                        DEPARTMENT_DESIGNATION_MAP[
                                          formData.department
                                        ] || []
                                      ).map((opt) => (
                                        <option key={opt} value={opt}>
                                          {opt}
                                        </option>
                                      ))}
                                      <option value="Custom">{t("Other (Type custom)...")}</option>
                                    </>
                                  )}
                                </select>
                                {formData.department &&
                                  formData.designation &&
                                  !(
                                    DEPARTMENT_DESIGNATION_MAP[
                                      formData.department
                                    ] || []
                                  ).includes(formData.designation) && (
                                    <input
                                      type="text"
                                      value={
                                        formData.designation ===
                                        "Custom Designation"
                                          ? ""
                                          : formData.designation
                                      }
                                      onChange={(e) =>
                                        setFormData({
                                          ...formData,
                                          designation:
                                            e.target.value ||
                                            "Custom Designation",
                                        })
                                      }
                                      className="form-input text-xs mt-1 border-dashed border-blue-300 focus:border-blue-500"
                                      placeholder={t("Type custom designation...")}
                                    />
                                  )}
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Reporting Manager")}</label>
                                <input
                                  type="text"
                                  value={formData.reportingManager || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      reportingManager: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("Manager Name")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Employment Type")}</label>
                                <select
                                  id="staff-contact-type"
                                  value={formData.contactType || "Internal"}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      contactType: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="Internal">{t("Staff (Internal Contact)")}</option>
                                  <option value="Contract">{t("Contract Staff")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Salary / Pay Amount")}</label>
                                <input
                                  type="number"
                                  value={formData.salary || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      salary: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("0.00")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Shift Timing")}</label>
                                <select
                                  value={formData.shiftTiming || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      shiftTiming: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Shift...")}</option>
                                  <option value="General Shift">{t("General Shift")}</option>
                                  <option value="Morning Shift">{t("Morning Shift")}</option>
                                  <option value="Evening Shift">{t("Evening Shift")}</option>
                                  <option value="Night Shift">{t("Night Shift")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Notice Period")}</label>
                                <select
                                  value={formData.noticePeriod || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      noticePeriod: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Notice Period...")}</option>
                                  <option value="15 Days">{t("15 Days")}</option>
                                  <option value="30 Days">{t("30 Days")}</option>
                                  <option value="60 Days">{t("60 Days")}</option>
                                  <option value="90 Days">{t("90 Days")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Probation Period")}</label>
                                <select
                                  value={formData.probationPeriod || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      probationPeriod: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Probation...")}</option>
                                  <option value="None">{t("None")}</option>
                                  <option value="1 Month">{t("1 Month")}</option>
                                  <option value="3 Months">{t("3 Months")}</option>
                                  <option value="6 Months">{t("6 Months")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Work Location / Branch")}</label>
                                <input
                                  type="text"
                                  value={formData.workLocation || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      workLocation: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Head Office, Branch A")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1 md:col-span-2">
                                <label className="form-label text-xs">{t("Duties / Operational Description")}</label>
                                <input
                                  type="text"
                                  value={formData.description || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      description: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("Add duties, approvals, and specific operational remarks...")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
