import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const IdentitySection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Identity */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "identity" ? null : "identity",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "identity"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">
                          <Fingerprint className="w-4 h-4 text-slate-500 dark:text-gray-400" /> Identity Details
                        </span>
                        {expandedSection === "identity" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "identity" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("Aadhaar Card Number")}</label>
                                <input
                                  type="text"
                                  value={formData.aadhaarCard || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      aadhaarCard: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 1234 5678 9012")}
                                  maxLength={19}
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("PAN Card Number")}</label>
                                <input
                                  type="text"
                                  value={formData.panCard || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      panCard: e.target.value.toUpperCase(),
                                    })
                                  }
                                  className="form-input font-mono uppercase"
                                  placeholder={t("e.g. ABCDE1234F")}
                                  maxLength={10}
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("Voter ID Card Number")}</label>
                                <input
                                  type="text"
                                  value={formData.voterIdCard || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      voterIdCard: e.target.value.toUpperCase(),
                                    })
                                  }
                                  className="form-input font-mono uppercase"
                                  placeholder={t("e.g. ABC1234567")}
                                />
                              </div>
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("Driving License")}</label>
                                <input
                                  type="text"
                                  value={formData.drivingLicense || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      drivingLicense: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. DL-1420110123456")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("UAN / PF Number")}</label>
                                <input
                                  type="text"
                                  value={formData.uanNumber || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      uanNumber: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono uppercase"
                                  placeholder={t("e.g. 100001234567")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("ESI Number")}</label>
                                <input
                                  type="text"
                                  value={formData.esiNumber || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      esiNumber: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono uppercase"
                                  placeholder={t("e.g. 31000123450001001")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("Passport Number")}</label>
                                <input
                                  type="text"
                                  value={formData.passportNumber || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      passportNumber: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono uppercase"
                                  placeholder={t("e.g. Z1234567")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-[11px] font-semibold text-gray-500 dark:text-gray-400">{t("Passport Expiry Date")}</label>
                                <input
                                  type="date"
                                  value={formData.passportExpiryDate || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      passportExpiryDate: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
