import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const NomineeDetailSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Nominee Detail */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "family_nominee" ? null : "family_nominee",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "family_nominee"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("🧑‍⚖️ Nominee Detail")}</span>
                        {expandedSection === "family_nominee" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "family_nominee" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Select Nominee From Family")}</label>
                                <select
                                  value={
                                    (formData.nomineeName && [formData.guardianName, formData.motherName, formData.husbandName, formData.wifeName].includes(formData.nomineeName))
                                      ? formData.nomineeName
                                      : "Other"
                                  }
                                  onChange={(e) => {
                                    const val = e.target.value;
                                    if (val === "Other") {
                                      setFormData({ ...formData, nomineeName: "", nomineeRelation: "" });
                                    } else {
                                      let rel = "";
                                      if (val === formData.guardianName) rel = "Father";
                                      else if (val === formData.motherName) rel = "Mother";
                                      else if (val === formData.husbandName) rel = "Husband";
                                      else if (val === formData.wifeName) rel = "Wife";
                                      
                                      setFormData({
                                        ...formData,
                                        nomineeName: val,
                                        nomineeRelation: rel,
                                      });
                                    }
                                  }}
                                  className="form-input"
                                >
                                  <option value="Other">{t("Custom / Other Details")}</option>
                                  {formData.guardianName && <option value={formData.guardianName}>{formData.guardianName} (Father)</option>}
                                  {formData.motherName && <option value={formData.motherName}>{formData.motherName} (Mother)</option>}
                                  {formData.husbandName && <option value={formData.husbandName}>{formData.husbandName} (Husband)</option>}
                                  {formData.wifeName && <option value={formData.wifeName}>{formData.wifeName} (Wife)</option>}
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Nominee Relation")}</label>
                                <select
                                  value={formData.nomineeRelation || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      nomineeRelation: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Relation...")}</option>
                                  <option value="Spouse">{t("Spouse")}</option>
                                  <option value="Husband">{t("Husband")}</option>
                                  <option value="Wife">{t("Wife")}</option>
                                  <option value="Father">{t("Father")}</option>
                                  <option value="Mother">{t("Mother")}</option>
                                  <option value="Brother">{t("Brother")}</option>
                                  <option value="Sister">{t("Sister")}</option>
                                  <option value="Son">{t("Son")}</option>
                                  <option value="Daughter">{t("Daughter")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Type Nominee Name Manually")}</label>
                                <input
                                  type="text"
                                  value={formData.nomineeName || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      nomineeName: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("e.g. Meera Sharma")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Nominee Phone Number")}</label>
                                <input
                                  type="text"
                                  value={formData.nomineePhone || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      nomineePhone: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                  placeholder={t("e.g. 9811001100")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
