import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const PersonalDetailSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Personal Detail */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "personal" ? null : "personal",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "personal"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("👤 Personal Details")}</span>
                        {expandedSection === "personal" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "personal" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Date of Birth")}</label>
                                <input
                                  type="date"
                                  value={formData.dateOfBirth || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      dateOfBirth: e.target.value,
                                    })
                                  }
                                  className="form-input font-mono"
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Marital Status")}</label>
                                <select
                                  value={formData.maritalStatus || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      maritalStatus: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Status...")}</option>
                                  <option value="Single">{t("Single")}</option>
                                  <option value="Married">{t("Married")}</option>
                                  <option value="Divorced">{t("Divorced")}</option>
                                  <option value="Widowed">{t("Widowed")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Gender")}</label>
                                <select
                                  id="staff-gender"
                                  value={formData.gender || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      gender: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Gender...")}</option>
                                  <option value="Male">{t("Male")}</option>
                                  <option value="Female">{t("Female")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Blood Group")}</label>
                                <select
                                  value={formData.bloodGroup || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      bloodGroup: e.target.value,
                                    })
                                  }
                                  className="form-input font-semibold text-gray-850 dark:text-gray-150"
                                >
                                  <option value="">{t("Select Blood Group...")}</option>
                                  <option value="A+">{t("A+ (A Positive)")}</option>
                                  <option value="A-">{t("A- (A Negative)")}</option>
                                  <option value="B+">{t("B+ (B Positive)")}</option>
                                  <option value="B-">{t("B- (B Negative)")}</option>
                                  <option value="AB+">{t("AB+ (AB Positive)")}</option>
                                  <option value="AB-">{t("AB- (AB Negative)")}</option>
                                  <option value="O+">{t("O+ (O Positive)")}</option>
                                  <option value="O-">{t("O- (O Negative)")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Nationality")}</label>
                                <select
                                  value={formData.nationality || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      nationality: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Nationality...")}</option>
                                  <option value="Indian">{t("Indian")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Religion")}</label>
                                <select
                                  value={formData.religion || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      religion: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Religion...")}</option>
                                  <option value="Hinduism">{t("Hinduism")}</option>
                                  <option value="Islam">{t("Islam")}</option>
                                  <option value="Christianity">{t("Christianity")}</option>
                                  <option value="Sikhism">{t("Sikhism")}</option>
                                  <option value="Buddhism">{t("Buddhism")}</option>
                                  <option value="Jainism">{t("Jainism")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Category")}</label>
                                <select
                                  value={formData.category || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      category: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Category...")}</option>
                                  <option value="General">{t("General")}</option>
                                  <option value="OBC">{t("OBC")}</option>
                                  <option value="SC">{t("SC")}</option>
                                  <option value="ST">{t("ST")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Mother Tongue")}</label>
                                <select
                                  value={formData.motherTongue || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      motherTongue: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Mother Tongue...")}</option>
                                  <option value="Assamese">{t("Assamese")}</option>
                                  <option value="Bengali">{t("Bengali")}</option>
                                  <option value="Bodo">{t("Bodo")}</option>
                                  <option value="Dogri">{t("Dogri")}</option>
                                  <option value="English">{t("English")}</option>
                                  <option value="Gujarati">{t("Gujarati")}</option>
                                  <option value="Hindi">{t("Hindi")}</option>
                                  <option value="Kannada">{t("Kannada")}</option>
                                  <option value="Kashmiri">{t("Kashmiri")}</option>
                                  <option value="Konkani">{t("Konkani")}</option>
                                  <option value="Maithili">{t("Maithili")}</option>
                                  <option value="Malayalam">{t("Malayalam")}</option>
                                  <option value="Manipuri">{t("Manipuri")}</option>
                                  <option value="Marathi">{t("Marathi")}</option>
                                  <option value="Nepali">{t("Nepali")}</option>
                                  <option value="Odia">{t("Odia")}</option>
                                  <option value="Punjabi">{t("Punjabi")}</option>
                                  <option value="Sanskrit">{t("Sanskrit")}</option>
                                  <option value="Santali">{t("Santali")}</option>
                                  <option value="Sindhi">{t("Sindhi")}</option>
                                  <option value="Tamil">{t("Tamil")}</option>
                                  <option value="Telugu">{t("Telugu")}</option>
                                  <option value="Urdu">{t("Urdu")}</option>
                                  <option value="Other">{t("Other")}</option>
                                </select>
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Known Languages")}</label>
                                <input
                                  type="text"
                                  value={Array.isArray(formData.knownLanguages) ? formData.knownLanguages.join(', ') : formData.knownLanguages || ""}
                                  onChange={(e) => {
                                    setFormData({
                                      ...formData,
                                      knownLanguages: e.target.value,
                                    });
                                  }}
                                  className="form-input"
                                  placeholder={t("e.g. English, Hindi, Marathi")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Physically Handicapped")}</label>
                                <select
                                  value={formData.physicallyHandicapped || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      physicallyHandicapped: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                >
                                  <option value="">{t("Select Option...")}</option>
                                  <option value="No">{t("No")}</option>
                                  <option value="Yes - VH">{t("Yes - Visually Handicapped")}</option>
                                  <option value="Yes - HH">{t("Yes - Hearing Handicapped")}</option>
                                  <option value="Yes - OH">{t("Yes - Orthopedically Handicapped")}</option>
                                </select>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
