import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const PhotoSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Photo */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "photo" ? null : "photo",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "photo"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("📷 Profile Photo")}</span>
                        {expandedSection === "photo" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "photo" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800">
                              <div className="flex flex-col sm:flex-row gap-4 items-center">
                                {/* Preview container */}
                                <div className="w-16 h-16 rounded-full overflow-hidden bg-slate-50 border border-slate-200 flex items-center justify-center text-slate-400 shadow-inner flex-shrink-0 dark:bg-slate-900 dark:border-slate-800">
                                  {formData.photoUrl ? (
                                    <img
                                      src={formData.photoUrl}
                                      alt="Preview"
                                      className="w-full h-full object-cover"
                                      referrerPolicy="no-referrer"
                                    />
                                  ) : (
                                    <span className="text-xl font-bold dark:text-slate-600">{t("S")}</span>
                                  )}
                                </div>

                                {/* Form input and upload triggers */}
                                <div className="flex-1 w-full space-y-2">
                                  <div
                                    onDragOver={(e) => e.preventDefault()}
                                    onDrop={(e) => {
                                      e.preventDefault();
                                      const file = e.dataTransfer.files?.[0];
                                      if (file) {
                                        const reader = new FileReader();
                                        reader.onloadend = () => {
                                          setFormData((prev) => ({
                                            ...prev,
                                            photoUrl: reader.result as string,
                                          }));
                                        };
                                        reader.readAsDataURL(file);
                                      }
                                    }}
                                    className="border border-dashed border-slate-350 hover:border-blue-500 bg-slate-50/50 hover:bg-blue-50/10 p-3 rounded-xl text-center cursor-pointer transition-all dark:border-slate-800 dark:bg-slate-900/40"
                                    onClick={() => {
                                      const fileInput = document.getElementById(
                                        "staff-photo-file-upload",
                                      );
                                      if (fileInput) fileInput.click();
                                    }}
                                  >
                                    <input
                                      type="file"
                                      id="staff-photo-file-upload"
                                      accept="image/*"
                                      className="hidden"
                                      onChange={(e) => {
                                        const file = e.target.files?.[0];
                                        if (file) {
                                          const reader = new FileReader();
                                          reader.onloadend = () => {
                                            setFormData((prev) => ({
                                              ...prev,
                                              photoUrl: reader.result as string,
                                            }));
                                          };
                                          reader.readAsDataURL(file);
                                        }
                                      }}
                                    />
                                    <div className="text-xs text-gray-600 dark:text-gray-400">
                                      <span className="text-blue-600 dark:text-blue-400 font-extrabold">{t("Click to upload")}</span>{" "}
                                      or drag and drop a portrait picture
                                    </div>
                                    <div className="text-[10px] text-gray-400">{t("Supports JPG, PNG, WebP")}</div>
                                  </div>

                                  <div className="flex flex-col sm:flex-row gap-2">
                                    <input
                                      type="text"
                                      value={
                                        formData.photoUrl &&
                                        !formData.photoUrl.startsWith("data:")
                                          ? formData.photoUrl
                                          : ""
                                      }
                                      onChange={(e) =>
                                        setFormData({
                                          ...formData,
                                          photoUrl: e.target.value,
                                        })
                                      }
                                      className="form-input text-xs"
                                      placeholder={t("Or paste an image URL...")}
                                    />
                                    <div className="flex gap-1.5 justify-end">
                                      <button
                                        type="button"
                                        onClick={() => {
                                          const randoms = [
                                            "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop",
                                            "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
                                            "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
                                            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
                                            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
                                            "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
                                          ];
                                          const current =
                                            formData.photoUrl || "";
                                          let selected =
                                            randoms[
                                              Math.floor(
                                                Math.random() * randoms.length,
                                              )
                                            ];
                                          while (selected === current) {
                                            selected =
                                              randoms[
                                                Math.floor(
                                                  Math.random() *
                                                    randoms.length,
                                                )
                                              ];
                                          }
                                          setFormData({
                                            ...formData,
                                            photoUrl: selected,
                                          });
                                        }}
                                        className="px-2.5 py-1.5 bg-indigo-50 border border-indigo-100 dark:bg-indigo-950/40 dark:border-indigo-900 rounded-lg text-indigo-700 dark:text-indigo-400 font-bold text-[11px] whitespace-nowrap hover:bg-indigo-100 transition-colors"
                                      >
                                        🎨 Random Portrait
                                      </button>
                                      {formData.photoUrl && (
                                        <button
                                          type="button"
                                          onClick={() =>
                                            setFormData({
                                              ...formData,
                                              photoUrl: "",
                                            })
                                          }
                                          className="px-2 py-1.5 bg-rose-50 border border-rose-100 dark:bg-rose-950/40 dark:border-rose-900 rounded-lg text-rose-600 dark:text-rose-400 font-bold text-[11px] hover:bg-rose-100 transition-colors"
                                        >
                                          Reset
                                        </button>
                                      )}
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
