import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, Fingerprint, Edit2, Trash2, FileCheck2, UserIcon } from 'lucide-react';
import { ContactFormSectionProps } from '../types';

export const SocialLinksSection: React.FC<ContactFormSectionProps> = (props) => {
  const { formData, setFormData, expandedSection, setExpandedSection, t, handleFileUpload, data, partyMasters, getAutoGeneratedCode } = props;
  
  return (
    <>
{/* Collapsible Section: Social & Links */}
                    <div className="col-span-full border-y border-slate-100 dark:border-slate-800 rounded-none overflow-hidden shadow-none mt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === "social_links" ? null : "social_links",
                          )
                        }
                        className="w-full flex items-center justify-between py-2 px-4 bg-slate-50 dark:bg-slate-900 font-bold text-gray-800 dark:text-gray-100 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-xs border-b border-transparent data-[open=true]:border-slate-100 dark:data-[open=true]:border-slate-800"
                        data-open={expandedSection === "social_links"}
                      >
                        <span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-gray-300">{t("🔗 Social & Links")}</span>
                        {expandedSection === "social_links" ? (
                          <ChevronUp className="w-4 h-4 text-gray-500" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-gray-500" />
                        )}
                      </button>

                      <AnimatePresence initial={false}>
                        {expandedSection === "social_links" && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                            transition={{ duration: 0.2 }}
                          >
                            <div className="p-4 bg-white dark:bg-gray-800 grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("LinkedIn Profile")}</label>
                                <input
                                  type="url"
                                  value={formData.linkedInUrl || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      linkedInUrl: e.target.value,
                                    })
                                  }
                                  className="form-input text-blue-600 dark:text-blue-400"
                                  placeholder={t("https://linkedin.com/in/username")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Twitter / X Profile")}</label>
                                <input
                                  type="url"
                                  value={formData.twitterUrl || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      twitterUrl: e.target.value,
                                    })
                                  }
                                  className="form-input text-sky-500 dark:text-sky-400"
                                  placeholder={t("https://twitter.com/username")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Personal Portfolio / Website")}</label>
                                <input
                                  type="url"
                                  value={formData.portfolioUrl || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      portfolioUrl: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("https://www.example.com")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("YouTube URL")}</label>
                                <input
                                  type="url"
                                  value={formData.youtubeUrl || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      youtubeUrl: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("https://youtube.com/...")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Instagram URL")}</label>
                                <input
                                  type="url"
                                  value={formData.instagramUrl || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      instagramUrl: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("https://instagram.com/...")}
                                />
                              </div>

                              <div className="form-field-wrapper col-span-1">
                                <label className="form-label text-xs">{t("Facebook URL")}</label>
                                <input
                                  type="url"
                                  value={formData.facebookUrl || ""}
                                  onChange={(e) =>
                                    setFormData({
                                      ...formData,
                                      facebookUrl: e.target.value,
                                    })
                                  }
                                  className="form-input"
                                  placeholder={t("https://facebook.com/...")}
                                />
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
    </>
  );
};
