export const INDIAN_BANKS = [
  "State Bank of India (SBI)",
  "HDFC Bank",
  "ICICI Bank",
  "Punjab National Bank (PNB)",
  "Axis Bank",
  "Canara Bank",
  "Bank of Baroda (BoB)",
  "Union Bank of India",
  "Bank of India",
  "Indian Bank",
  "Central Bank of India",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "Yes Bank",
  "IDFC FIRST Bank",
  "Federal Bank",
  "South Indian Bank",
  "Karur Vysya Bank",
  "City Union Bank",
  "Bandhan Bank",
  "RBL Bank",
  "Jammu & Kashmir Bank",
  "Karnataka Bank",
  "Tamilnad Mercantile Bank",
  "Dhanlaxmi Bank",
  "CSB Bank",
  "Nainital Bank",
  "Citibank India",
  "Standard Chartered Bank",
  "HSBC Bank India",
  "Saraswat Bank",
  "Cosmos Bank",
  "Shamrao Vithal Co-operative Bank (SVC)",
  "Abhyudaya Co-operative Bank",
  "Bharat Co-operative Bank",
  "TJSB Sahakari Bank",
  "Kalupur Commercial Co-operative Bank"
].sort();
