export const BUSINESS_SUBDOMAINS: Record<string, { label: string; value: string }[]> = {
  grocery: [
    { label: "All Grocery & Supermarket", value: "all" },
    { label: "Grocery Mart", value: "grocery_mart" },
    { label: "Supermarket", value: "supermarket" },
    { label: "Kirana Store", value: "kirana" },
    { label: "General Store", value: "general_store" },
    { label: "Organic Food Store", value: "organic_food" },
    { label: "Dairy & Milk Products", value: "dairy" },
    { label: "Dry Fruits & Spices", value: "dry_fruits" },
  ],
  clothes: [
    { label: "All Apparel & Clothing", value: "all" },
    { label: "Men's Apparel", value: "mens_apparel" },
    { label: "Women's Boutique", value: "womens_boutique" },
    { label: "Kids Wear", value: "kids_wear" },
    { label: "Footwear / Shoes", value: "footwear" },
    { label: "Sportswear & Activewear", value: "sportswear" },
    { label: "Accessories & Bags", value: "accessories" },
    { label: "Uniforms & Workwear", value: "uniforms" },
    { label: "Hosiery & Innerwear", value: "hosiery" },
  ],
  medical: [
    { label: "All Medical & Pharmacy", value: "all" },
    { label: "General Pharmacy", value: "pharmacy" },
    { label: "Ayurvedic / Herbal", value: "ayurvedic" },
    { label: "Surgical Instruments", value: "surgical" },
    { label: "Veterinary Medicine", value: "veterinary" },
    { label: "Homeopathy & Alternative", value: "homeopathy" },
    { label: "Medical Equipment", value: "medical_equipment" },
  ],
  electronics: [
    { label: "All Electronics & Gadgets", value: "all" },
    { label: "Mobile / Smartphones", value: "mobile" },
    { label: "Computers & Laptops", value: "computers" },
    { label: "Consumer Appliances", value: "appliances" },
    { label: "Audio & Video Equipment", value: "audio_video" },
    { label: "Smart Home & IoT", value: "smart_home" },
    { label: "Cameras & Photography", value: "cameras" },
    { label: "Electronic Components", value: "components" },
  ],
  hardware: [
    { label: "All Hardware & Building", value: "all" },
    { label: "Cement & Building Materials", value: "building_materials" },
    { label: "Paints & Chemicals", value: "paints" },
    { label: "Sanitary & Plumbing", value: "sanitary" },
    { label: "Electricals & Lighting", value: "electricals" },
    { label: "Tools & Machinery", value: "tools" },
    { label: "Timber, Plywood & Glass", value: "timber" },
    { label: "Tiles & Flooring", value: "tiles" },
  ],
  fmcg: [
    { label: "All FMCG Goods", value: "all" },
    { label: "Food & Beverages", value: "food_beverages" },
    { label: "Personal Care", value: "personal_care" },
    { label: "Home Care & Cleaning", value: "home_care" },
    { label: "Packaged Snacks & Confectionery", value: "snacks" },
  ],
  kitchen: [
    { label: "All Kitchen Utensils", value: "all" },
    { label: "Pots & Pans", value: "pots_pans" },
    { label: "Cutlery & Tableware", value: "cutlery" },
    { label: "Kitchen Appliances", value: "kitchen_appliances" },
    { label: "Glassware & Crockery", value: "glassware" },
    { label: "Plasticware & Storage", value: "plasticware" },
  ],
  food: [
    { label: "All Food Services", value: "all" },
    { label: "Restaurant", value: "restaurant" },
    { label: "Cafe", value: "cafe" },
    { label: "Fast Food", value: "fast_food" },
    { label: "Cloud Kitchen / Delivery Only", value: "cloud_kitchen" },
    { label: "Catering Services", value: "catering" },
    { label: "Sweet Shop / Confectionery", value: "sweet_shop" },
  ],
  furniture: [
    { label: "All Furniture", value: "all" },
    { label: "Home Furniture", value: "home_furniture" },
    { label: "Office Furniture", value: "office_furniture" },
    { label: "Outdoor & Garden Furniture", value: "outdoor_furniture" },
    { label: "Mattresses & Bedding", value: "mattresses" },
    { label: "Furnishings & Curtains", value: "furnishings" },
  ],
  automotive: [
    { label: "All Automotive", value: "all" },
    { label: "Auto Parts", value: "auto_parts" },
    { label: "Car Wash", value: "car_wash" },
    { label: "Repair Shop", value: "repair_shop" },
    { label: "Tyres & Batteries", value: "tyres" },
    { label: "Accessories & Decor", value: "auto_accessories" },
    { label: "Vehicle Dealership", value: "dealership" },
  ],
  beauty: [
    { label: "All Beauty & Wellness", value: "all" },
    { label: "Salon", value: "salon" },
    { label: "Spa", value: "spa" },
    { label: "Cosmetics Shop", value: "cosmetics" },
    { label: "Tattoo & Piercing Parlor", value: "tattoo" },
    { label: "Fitness Center / Gym", value: "fitness" },
  ],
  it: [
    { label: "All IT & Tech Services", value: "all" },
    { label: "Software Development", value: "software" },
    { label: "IT Consulting", value: "it_consulting" },
    { label: "Computer Repair", value: "repair" },
    { label: "Web & Digital Marketing", value: "digital_marketing" },
    { label: "Networking & Security", value: "networking" },
  ],
  agriculture: [
    { label: "All Agriculture & Farming", value: "all" },
    { label: "Farming Equipment", value: "farming_equipment" },
    { label: "Fertilizers & Pesticides", value: "fertilizers" },
    { label: "Seeds & Plants", value: "seeds" },
    { label: "Poultry & Livestock", value: "poultry" },
    { label: "Produce Trading / Mandi", value: "produce_trading" },
  ],
  professional: [
    { label: "All Professional Services", value: "all" },
    { label: "Architecture & Interior Design", value: "architecture" },
    { label: "Marketing / Advertising", value: "marketing" },
    { label: "Business Consulting", value: "business_consulting" },
  ],
  finance: [
    { label: "All Financial & Legal", value: "all" },
    { label: "Chartered Accountant (CA)", value: "ca" },
    { label: "Accountant / Bookkeeper", value: "accountant" },
    { label: "Lawyer / Advocate", value: "lawyer" },
    { label: "Tax Consultant", value: "tax_consultant" },
    { label: "Insurance Agent", value: "insurance_agent" },
  ],
  education: [
    { label: "All Education & Training", value: "all" },
    { label: "School / College", value: "school" },
    { label: "Coaching / Tuition Center", value: "coaching" },
    { label: "Online Tutor / Courses", value: "tutor" },
    { label: "Music & Dance Classes", value: "music_dance" },
    { label: "Vocational Training", value: "vocational" },
  ],
  healthcare: [
    { label: "All Healthcare Professionals", value: "all" },
    { label: "Doctor / Clinic", value: "doctor" },
    { label: "Hospital / Nursing Home", value: "hospital" },
    { label: "Dentist", value: "dentist" },
    { label: "Pathology Lab / Diagnostics", value: "pathology" },
    { label: "Physiotherapy", value: "physiotherapy" },
  ],
  trades: [
    { label: "All Trades & Home Services", value: "all" },
    { label: "Carpenter / Woodwork", value: "carpenter" },
    { label: "Plumber / Sanitary Service", value: "plumber" },
    { label: "Electrician / Electrical Service", value: "electrician" },
    { label: "AC Repair & Maintenance", value: "ac_repair" },
    { label: "Pest Control", value: "pest_control" },
    { label: "Cleaning Services", value: "cleaning" },
    { label: "Civil Contractor / Mason", value: "mason" },
  ],
  travel: [
    { label: "All Travel & Hospitality", value: "all" },
    { label: "Hotel / Lodge", value: "hotel" },
    { label: "Travel Agency / Booking", value: "travel_agency" },
    { label: "Tour Operator", value: "tour_operator" },
    { label: "Cab / Taxi Service", value: "taxi" },
  ],
  logistics: [
    { label: "All Logistics & Transport", value: "all" },
    { label: "Courier & Parcel Service", value: "courier" },
    { label: "Packers & Movers", value: "packers_movers" },
    { label: "Transport & Cargo", value: "transport" },
    { label: "Warehousing / Storage", value: "warehousing" },
  ],
  events: [
    { label: "All Entertainment & Events", value: "all" },
    { label: "Event Planner / Decorator", value: "event_planner" },
    { label: "Photography & Videography", value: "photography" },
    { label: "DJ & Sound Services", value: "dj_sound" },
    { label: "Marriage Hall / Banquet", value: "banquet" },
    { label: "Tent House / Catering", value: "tent_house" },
  ],
  real_estate: [
    { label: "All Real Estate", value: "all" },
    { label: "Real Estate Brokerage / Agent", value: "brokerage" },
    { label: "Builder / Developer", value: "builder" },
    { label: "Property Management", value: "property_management" },
  ],
  manufacturing: [
    { label: "All Manufacturing", value: "all" },
    { label: "Textile Manufacturing", value: "textile" },
    { label: "Metal Fabrication", value: "metal" },
    { label: "Plastic Products", value: "plastic" },
    { label: "Food Processing & Packaging", value: "food_processing" },
    { label: "Chemical & Pharmaceutical", value: "chemical" },
    { label: "Paper & Printing", value: "printing" },
    { label: "Wood & Timber Processing", value: "wood_processing" },
  ],
  other: [
    { label: "All Other Business Types", value: "all" },
    { label: "Other Business Type", value: "other_business" },
  ],
};

export const DOMAIN_CATEGORIES: Record<string, { label: string; value: string }[]> = {
  product: [
    { value: "grocery", label: "Grocery Mart / Supermarket / Kirana" },
    { value: "clothes", label: "Apparel / Clothes / Boutique" },
    { value: "medical", label: "Medical Store / Pharmacy" },
    { value: "electronics", label: "Electronics & Gadgets" },
    { value: "hardware", label: "Hardware / Paint / Construction Supplies" },
    { value: "fmcg", label: "FMCG (Consumer Goods)" },
    { value: "kitchen", label: "Kitchen Utensils & Appliances" },
    { value: "furniture", label: "Furniture & Home Decor" },
    { value: "automotive", label: "Automotive / Auto Parts" },
    { value: "agriculture", label: "Agriculture & Farming" },
    { value: "manufacturing", label: "Heavy Duty & Manufacturing" },
    { value: "other", label: "Other Products" },
  ],
  service: [
    { value: "food", label: "Restaurant / Cafe / Food" },
    { value: "beauty", label: "Beauty / Salon / Personal Care" },
    { value: "it", label: "IT & Software / Electronics Repair" },
    {
      value: "trades",
      label: "Trades & Home Services (Carpenter, Plumber, Pest Control)",
    },
    { value: "travel", label: "Travel, Tourism & Hospitality" },
    { value: "logistics", label: "Logistics, Transport & Movers" },
    { value: "events", label: "Entertainment, Events & Photography" },
    { value: "real_estate", label: "Real Estate & Construction Builder" },
    { value: "other", label: "Other Services" },
  ],
  professional: [
    { value: "professional", label: "Professional & Consulting Services" },
    { value: "finance", label: "Finance, Legal & Accounting (CA, Lawyer)" },
    { value: "education", label: "Education, Tutor, Coaching" },
    { value: "healthcare", label: "Doctors, Clinics, Hospitals & Healthcare" },
    { value: "other", label: "Other Professional Services" },
  ],
};

export const BUSINESS_ROLES: Record<string, { label: string; value: string }[]> = {
  product: [
    { value: "retailer", label: "Retailer (B2C)" },
    { value: "wholesaler", label: "Wholesaler (B2B)" },
    { value: "distributor", label: "Distributor / Stockist" },
    { value: "manufacturer", label: "Manufacturer / Producer" },
    { value: "dealer", label: "Dealer / Franchisee" },
    { value: "importer_exporter", label: "Importer / Exporter" },
    { value: "dropshipper", label: "Dropshipper" },
    { value: "ecommerce_seller", label: "E-Commerce Seller" },
    { value: "other", label: "Other (Product Based)" },
  ],
  service: [
    { value: "service_provider", label: "General Service Provider" },
    { value: "contractor", label: "Contractor / Builder" },
    { value: "repair_maintenance", label: "Repair & Maintenance" },
    { value: "logistics", label: "Logistics / Transporter" },
    { value: "hospitality", label: "Hospitality & Events" },
    { value: "it_software", label: "IT & Software Services" },
    { value: "agency", label: "Agency (Marketing/Ad/Design)" },
    { value: "bpo_kpo", label: "BPO / KPO" },
    { value: "other", label: "Other (Service Based)" },
  ],
  professional: [
    { value: "freelancer", label: "Independent Freelancer" },
    { value: "consultant", label: "Consultant / Advisor" },
    { value: "legal", label: "Legal Practitioner" },
    { value: "financial", label: "Financial Professional (CA/CPA)" },
    { value: "healthcare", label: "Medical Professional / Clinic" },
    { value: "architect", label: "Architect / Interior Designer" },
    { value: "educator", label: "Educator / Coaching" },
    { value: "other", label: "Other (Professional)" },
  ],
};
