import { ClassificationProfileInfoSection } from './views/ClassificationProfileInfoSection';
import { GeneralCategorySection } from './views/GeneralCategorySection';
import { ContactModeofContactSection } from './views/ContactModeofContactSection';
import { PersonalDetailSection } from './views/PersonalDetailSection';
import { EducationQualificationSection } from './views/EducationQualificationSection';
import { ExperienceDetailSection } from './views/ExperienceDetailSection';
import { FamilyDetailSection } from './views/FamilyDetailSection';
import { EmploymentStatusSection } from './views/EmploymentStatusSection';
import { AddressSection } from './views/AddressSection';
import { IdentitySection } from './views/IdentitySection';
import { NomineeDetailSection } from './views/NomineeDetailSection';
import { SocialLinksSection } from './views/SocialLinksSection';
import { PhotoSection } from './views/PhotoSection';
import { BankDetailSection } from './views/BankDetailSection';
import { AssetsEquipmentSection } from './views/AssetsEquipmentSection';
import { ComplianceVerificationSection } from './views/ComplianceVerificationSection';
import { DocumentsProofsSection } from './views/DocumentsProofsSection';
import { BusinessProfileSection } from './views/BusinessProfileSection';
import { AddressInfoSection } from './views/AddressInfoSection';
import { FinanceBankingDetailsSection } from './views/FinanceBankingDetailsSection';
import { useLanguage } from '../../../../../context/LanguageContext';
import React from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { CancelIcon } from '../../../../icons/IconComponents';
import { ChevronDown, ChevronUp, Fingerprint } from 'lucide-react'; // Adjust imports as necessary

// Fallback icons if not present in IconComponents
import { Edit2, Trash2 } from 'lucide-react';

const DEPARTMENT_DESIGNATION_MAP: Record<string, string[]> = {
  Management: ["General Manager & Operations Director", "Chief Executive Officer (CEO)", "Chief Operating Officer (COO)", "Operations Director", "Administrative Head"],
  "Marketing & Ad": ["Lead Digital Advertiser & Brand Strategist", "PPC & AdWords Marketing Consultant", "Digital Marketing Executive", "Social Media Campaign Manager", "Ad Copywriter & Content Marketer"],
  Finance: ["Finance & Taxation Manager", "Senior Accountant & Bookkeeper", "Accounts Assistant", "Auditor & Tax Consultant", "Billing & Invoice Specialist"],
  Publishing: ["Publisher Relations Specialist", "Acquisitions & Contracting Manager", "Rights & Licensing Director", "Publishing Operations Supervisor"],
  "Logistics & Supply": ["Warehouse & Inventory Supervisor", "Logistics & Distribution Coordinator", "Storekeeper", "Inventory Auditor & Quality Analyst"],
  "Customer Success": ["Senior Customer Relations Manager", "Customer Success Executive", "Technical Support Specialist", "Customer Helpdesk Coordinator"],
  "Human Resources": ["Human Resources & Payroll Lead", "HR Operations Manager", "Talent Acquisition & Onboarding executive", "Recruitment & Training Coordinator"],
  "Sales & Distribution": ["Sales & Retail Channel Manager", "Channel Distribution Specialist", "Institutional Sales Consultant", "Retail Relations Executive"],
  "Editorial & Content": ["Senior Editorial & Content Acquisition Head", "Acquisition Editor", "Senior Proofreader & Fact-checker", "Royalty Specialist"],
  "Information Technology": ["Principal System & DevOps Engineer", "Systems & Network Administrator", "IT Support Team Lead", "Database Administrator", "OCR Integration Developer"],
};
const DEPARTMENT_OPTIONS = Object.keys(DEPARTMENT_DESIGNATION_MAP);

export const ContactFormModal = ({
  isOpen,
  onClose,
  formData,
  setFormData,
  editingId,
  handleSaveUnified,
  handleFileUpload,
  setExpandedSection,
  expandedSection,
  formSettings,
  data,
  partyMasters,
  getAutoGeneratedCode
}: any) => {
  const { t, formatNumber  } = useLanguage();

  const props = {
    formData, setFormData, expandedSection, setExpandedSection, 
    t, handleFileUpload, data, partyMasters, getAutoGeneratedCode
  };


  if (!isOpen) return null;

  return (
    <>
      {/* Unified Contact Modal (Supports Staff, Customer, Vendor, Partner dynamically!) */}
      {typeof document !== "undefined" && document.getElementById("main-content")
        ? createPortal(
            <div className={`absolute inset-0 bg-black/40 backdrop-blur-sm z-[100] flex items-center justify-center ${formSettings.currentModalMode === 'fullscreen' ? 'p-0' : 'p-4 sm:p-6 md:p-8'}`}>
              <div className={`bg-white w-full h-full overflow-hidden flex flex-col dark:bg-gray-800 border border-gray-200 dark:border-gray-700 shadow-2xl animate-in zoom-in-95 ${formSettings.currentModalMode === 'fullscreen' ? 'rounded-none max-w-full max-h-full' : 'rounded-2xl max-w-5xl max-h-[90vh]'}`}>
                <div className="flex justify-between items-center px-4 py-2 border-b border-gray-100 bg-gray-50/50 dark:border-gray-800 shrink-0">
                  <h2 className="font-bold text-base text-gray-900 flex items-center dark:text-white">
                    {editingId ? t("Edit") : t("Add")} {formData.unifiedType === "Staff" ? t("Staff") : formData.unifiedType === "Customer" ? t("Customer") : formData.unifiedType === "Vendor" ? t("Vendor") : formData.unifiedType === "Partner" ? t("Partner") : formData.unifiedType || t("Staff")}{" "}
                    {t("Contact")}
                  </h2>
                  <div className="flex items-center space-x-2">
                <button
                  onClick={() => onClose(false)}
                  className="text-gray-400 hover:text-gray-600 transition-colors p-2 hover:bg-gray-100 rounded-full dark:hover:bg-gray-600"
                >
                  <CancelIcon className="w-5 h-5" />
                </button>
              </div>
            </div>

            <div className="overflow-y-auto flex-1 py-4 px-0 space-y-2 custom-scrollbar">
              <div className="form-grid gap-4">
                                    <ClassificationProfileInfoSection {...props} />

                {/* Conditionally Render fields for Staff */}
                {(formData.unifiedType === "Staff" ||
                  !formData.unifiedType) && (
                  <>
                                        <GeneralCategorySection {...props} />

                                        <ContactModeofContactSection {...props} />

                                        <PersonalDetailSection {...props} />

                                        <EducationQualificationSection {...props} />

                                        <ExperienceDetailSection {...props} />

                                        <FamilyDetailSection {...props} />

                                        <EmploymentStatusSection {...props} />

                                        <AddressSection {...props} />

                                        <IdentitySection {...props} />

                                        <NomineeDetailSection {...props} />

                                        <SocialLinksSection {...props} />

                                        <PhotoSection {...props} />

                                        <BankDetailSection {...props} />

                                        <AssetsEquipmentSection {...props} />

                                        <ComplianceVerificationSection {...props} />

                                        <DocumentsProofsSection {...props} />
                  </>
                )}

                {/* Conditionally Render fields for Customers / Vendors / Partners */}
                {formData.unifiedType && formData.unifiedType !== "Staff" && (
                  <>
                                        <BusinessProfileSection {...props} />

                                        <AddressInfoSection {...props} />

                                        <FinanceBankingDetailsSection {...props} />
                  </>
                )}
              </div>
            </div>

            <div className="flex space-x-3 px-4 py-3 border-t border-gray-100 bg-gray-50/50 dark:border-gray-800">
              <button
                onClick={() => onClose(false)}
                className="flex-1 py-2 bg-white border border-gray-200 text-gray-700 font-bold rounded-xl hover:bg-gray-50 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-200 hover:dark:bg-gray-700 transition"
              >
                {t("Cancel")}
              </button>
              <button
                onClick={handleSaveUnified}
                className="flex-1 py-2 bg-blue-600 text-white font-bold rounded-xl hover:bg-blue-700 shadow-md shadow-blue-200 transition"
              >{t("Save Changes")}</button>
            </div>
          </div>
        </div>,
        document.getElementById("main-content")!
      ) : null}

      
    </>
  );
};
