export interface ContactFormSectionProps {
  formData: any;
  setFormData: (val: any) => void;
  expandedSection: string | null;
  setExpandedSection: (val: string | null) => void;
  t: (key: string) => string;
  data?: any;
  partyMasters?: any;
  getAutoGeneratedCode?: any;
  handleFileUpload?: any;
  // If there are others, we will pass them along. Any is fine for flexibility.
  [key: string]: any;
}
