export const INVOICE_FONTS = [
    { id: 'Default', label: 'Theme Default', category: 'Smart' },
    { id: 'Inter', label: 'Inter', category: 'Modern Sans' },
    { id: 'Roboto', label: 'Roboto', category: 'Clean Sans' },
    { id: 'Open Sans', label: 'Open Sans', category: 'Neutral Sans' },
    { id: 'Montserrat', label: 'Montserrat', category: 'Geometric Sans' },
    { id: 'Lato', label: 'Lato', category: 'Friendly Sans' },
    { id: 'Poppins', label: 'Poppins', category: 'Geometric Sans' },
    { id: 'Playfair Display', label: 'Playfair Display', category: 'Elegant Serif' },
    { id: 'Merriweather', label: 'Merriweather', category: 'Readable Serif' },
    { id: 'PT Serif', label: 'PT Serif', category: 'Classic Serif' },
    { id: 'Source Serif Pro', label: 'Source Serif Pro', category: 'Formal Serif' },
    { id: 'JetBrains Mono', label: 'JetBrains Mono', category: 'Developer Mono' },
    { id: 'Roboto Mono', label: 'Roboto Mono', category: 'Technical Mono' },
    { id: 'Space Grotesk', label: 'Space Grotesk', category: 'Display Art' },
    { id: 'Oswald', label: 'Oswald', category: 'Display Narrow' },
    { id: 'Raleway', label: 'Raleway', category: 'Display Thin' },
    { id: 'Work Sans', label: 'Work Sans', category: 'Display Bold' },
    { id: 'Ubuntu', label: 'Ubuntu', category: 'Brand Sans' },
    { id: 'Fira Sans', label: 'Fira Sans', category: 'Technical Sans' },
    { id: 'Nunito', label: 'Nunito', category: 'Rounded' },
    { id: 'Quicksand', label: 'Quicksand', category: 'Soft Rounded' },
    { id: 'Josefin Sans', label: 'Josefin Sans', category: 'Vintage Sans' },
    { id: 'PT Sans', label: 'PT Sans', category: 'Modern Sans' },
    { id: 'Source Sans Pro', label: 'Source Sans Pro', category: 'Professional Sans' },
];

export const DEFAULT_INVOICE_SETTINGS = {
    itemsPerFirstPage: 12,
    itemsPerSecondPage: 15,
    itemsPerLastPage: 10,
    selectedUser: 'Admin',
    headerDisplay: 'First Page Only',
    pageSubtotalDisplay: 'All Pages',
    showPageNumber: 'Yes',
    pageNumberLocation: 'Bottom',
    pageNumberAlignment: 'Right',
    pageNumberFormat: 'Page 1 of 3',
    showLogo: true,
    showHeader: true,
    showBilling: true,
    showHSN: true,
    showQty: true,
    showRate: true,
    showMrp: true,
    showDiscountPercentage: true,
    showDiscountAmount: true,
    showTaxDetails: true,
    showAmountInWords: true,
    showNarration: true,
    showFooterNotes: true,
    showTaxSummary: true,
    showHsnSummary: true,
    showSignature: true,
    showCustomerSign: true,
    compactMode: true,
    ultraCompactMode: false,
    ultraCleanMode: false,
    useGrayScale: false,
    pageSize: 'A4',
    pageOrientation: 'Portrait',
    pageMargin: 'Narrow',
    marginTop: 0.5,
    marginBottom: 0.5,
    marginLeft: 0.5,
    marginRight: 0.5,
    designLayout: 'Modern',
    colorPalette: 'Default',
    fontFamily: 'Default',
    baseFontSize: 10,
    headingScale: 1.2,
    lineHeight: 1,
    letterSpacing: 0,
    wordSpacing: 0,
    paragraphSpacing: 0,
    headerSpacing: 0,
    plainSpacing: 0,
    fontWeight: '400',
    textTransform: 'default',
    sectionStyles: {
        lineItem: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        header: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        subheader: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        companyName: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        companyAddress: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        partyName: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        partyAddress: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        tableHeader: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        amountInWords: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        narration: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        taxDetails: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        signatures: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 },
        grandTotal: { color: '', weight: '', transform: 'default', family: 'Default', size: '', marginTop: '', marginBottom: '', verticalShift: 0, height: 0 }
    }
};
