
import React from 'react';

const Icon: React.FC<{ name: string; className?: string }> = ({ name, className }) => (
  <span className={`material-symbols-outlined ${className || ''}`}>{name}</span>
);

export const DashboardIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="dashboard" className={className} />;
export const MastersIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="group" className={className} />;
export const VouchersIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="receipt_long" className={className} />;
export const ReportsIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="assessment" className={className} />;
export const AIToolsIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="auto_awesome" className={className} />;
export const SettingsIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="settings" className={className} />;
export const MenuIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="menu" className={className} />;
export const FilterListIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="filter_list" className={className} />;
export const SearchIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="search" className={className} />;
export const NotificationsIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="notifications" className={className} />;
export const AccountIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="account_circle" className={className} />;
export const UploadFileIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="upload_file" className={className} />;
export const ArrowForwardIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="arrow_forward" className={className} />;
export const ArrowBackIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="arrow_back" className={className} />;
export const CheckCircleIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="check_circle" className={className} />;
export const CancelIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="cancel" className={className} />;
export const InfoIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="info" className={className} />;
export const EditIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="edit" className={className} />;
export const DownloadIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="download" className={className} />;
export const PrintIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="print" className={className} />;
export const UndoIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="undo" className={className} />;
export const UploadIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="upload" className={className} />;
export const ClearAllIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="clear_all" className={className} />;
export const ExpandMoreIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="expand_more" className={className} />;
export const ExpandLessIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="expand_less" className={className} />;
export const ChevronRightIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="chevron_right" className={className} />;
export const ChevronDownIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="keyboard_arrow_down" className={className} />;
export const AddIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="add" className={className} />;
export const WarningIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="warning" className={className} />;
export const ErrorIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="error" className={className} />;
export const MoreHorizIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="more_horiz" className={className} />;
export const MoreVertIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="more_vert" className={className} />;
export const DeleteIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="delete" className={className} />;
export const ContentCopyIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="content_copy" className={className} />;
export const HistoryIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="history" className={className} />;
export const LayoutIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="view_quilt" className={className} />;
export const VisibilityIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="visibility" className={className} />;
export const InventoryIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="inventory_2" className={className} />;
export const UomIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="square_foot" className={className} />;
export const SortIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="sort" className={className} />;
export const BrandIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="label" className={className} />;
export const CategoryIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="category" className={className} />;
export const PriceListIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="payments" className={className} />;
export const TrendingUpIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="trending_up" className={className} />;
export const MapIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="map" className={className} />;
export const TaxIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="percent" className={className} />;
export const BankIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="account_balance" className={className} />;
export const PieChartIcon: React.FC<{ name?: string, size?: number, className?: string }> = ({ size, className }) => <Icon name="pie_chart" className={className} />;
export const SecurityIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="shield" className={className} />;
export const AdminIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="admin_panel_settings" className={className} />;
export const CodeIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="code" className={className} />;
export const PdfIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="picture_as_pdf" className={className} />;
export const ExcelIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="table_chart" className={className} />;
export const ImageIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="image" className={className} />;
export const FileIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="description" className={className} />;
export const AutoFixHighIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="auto_fix_high" className={className} />;
export const SaveIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="save" className={className} />;
export const AddBoxIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="add_box" className={className} />;
export const MoveToInboxIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="move_to_inbox" className={className} />;
export const SwapHorizIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="swap_horiz" className={className} />;
export const SunIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="light_mode" className={className} />;
export const MoonIcon: React.FC<{ className?: string }> = ({ className }) => <Icon name="dark_mode" className={className} />;
